/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.food.friendly.program.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FFPBeneficiaryVersion service. Represents a row in the &quot;FFPB_RegistrationVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>bd.gov.dgfood.food.friendly.program.model.impl.FFPBeneficiaryVersionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>bd.gov.dgfood.food.friendly.program.model.impl.FFPBeneficiaryVersionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FFPBeneficiaryVersion
 * @generated
 */
@ProviderType
public interface FFPBeneficiaryVersionModel
	extends BaseModel<FFPBeneficiaryVersion>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ffp beneficiary version model instance should use the {@link FFPBeneficiaryVersion} interface instead.
	 */

	/**
	 * Returns the primary key of this ffp beneficiary version.
	 *
	 * @return the primary key of this ffp beneficiary version
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ffp beneficiary version.
	 *
	 * @param primaryKey the primary key of this ffp beneficiary version
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the beneficiary version ID of this ffp beneficiary version.
	 *
	 * @return the beneficiary version ID of this ffp beneficiary version
	 */
	public long getBeneficiaryVersionId();

	/**
	 * Sets the beneficiary version ID of this ffp beneficiary version.
	 *
	 * @param beneficiaryVersionId the beneficiary version ID of this ffp beneficiary version
	 */
	public void setBeneficiaryVersionId(long beneficiaryVersionId);

	/**
	 * Returns the beneficiary ID of this ffp beneficiary version.
	 *
	 * @return the beneficiary ID of this ffp beneficiary version
	 */
	public long getBeneficiaryId();

	/**
	 * Sets the beneficiary ID of this ffp beneficiary version.
	 *
	 * @param beneficiaryId the beneficiary ID of this ffp beneficiary version
	 */
	public void setBeneficiaryId(long beneficiaryId);

	/**
	 * Returns the group ID of this ffp beneficiary version.
	 *
	 * @return the group ID of this ffp beneficiary version
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this ffp beneficiary version.
	 *
	 * @param groupId the group ID of this ffp beneficiary version
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this ffp beneficiary version.
	 *
	 * @return the company ID of this ffp beneficiary version
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ffp beneficiary version.
	 *
	 * @param companyId the company ID of this ffp beneficiary version
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the version of this ffp beneficiary version.
	 *
	 * @return the version of this ffp beneficiary version
	 */
	public double getVersion();

	/**
	 * Sets the version of this ffp beneficiary version.
	 *
	 * @param version the version of this ffp beneficiary version
	 */
	public void setVersion(double version);

	/**
	 * Returns the name of this ffp beneficiary version.
	 *
	 * @return the name of this ffp beneficiary version
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this ffp beneficiary version.
	 *
	 * @param name the name of this ffp beneficiary version
	 */
	public void setName(String name);

	/**
	 * Returns the mobile number of this ffp beneficiary version.
	 *
	 * @return the mobile number of this ffp beneficiary version
	 */
	@AutoEscape
	public String getMobileNumber();

	/**
	 * Sets the mobile number of this ffp beneficiary version.
	 *
	 * @param mobileNumber the mobile number of this ffp beneficiary version
	 */
	public void setMobileNumber(String mobileNumber);

	/**
	 * Returns the national ID of this ffp beneficiary version.
	 *
	 * @return the national ID of this ffp beneficiary version
	 */
	public long getNationalId();

	/**
	 * Sets the national ID of this ffp beneficiary version.
	 *
	 * @param nationalId the national ID of this ffp beneficiary version
	 */
	public void setNationalId(long nationalId);

	/**
	 * Returns the email address of this ffp beneficiary version.
	 *
	 * @return the email address of this ffp beneficiary version
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this ffp beneficiary version.
	 *
	 * @param emailAddress the email address of this ffp beneficiary version
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the card number of this ffp beneficiary version.
	 *
	 * @return the card number of this ffp beneficiary version
	 */
	@AutoEscape
	public String getCardNumber();

	/**
	 * Sets the card number of this ffp beneficiary version.
	 *
	 * @param cardNumber the card number of this ffp beneficiary version
	 */
	public void setCardNumber(String cardNumber);

	/**
	 * Returns the date of birth of this ffp beneficiary version.
	 *
	 * @return the date of birth of this ffp beneficiary version
	 */
	public Date getDateOfBirth();

	/**
	 * Sets the date of birth of this ffp beneficiary version.
	 *
	 * @param dateOfBirth the date of birth of this ffp beneficiary version
	 */
	public void setDateOfBirth(Date dateOfBirth);

	/**
	 * Returns the gender of this ffp beneficiary version.
	 *
	 * @return the gender of this ffp beneficiary version
	 */
	public int getGender();

	/**
	 * Sets the gender of this ffp beneficiary version.
	 *
	 * @param gender the gender of this ffp beneficiary version
	 */
	public void setGender(int gender);

	/**
	 * Returns the father name of this ffp beneficiary version.
	 *
	 * @return the father name of this ffp beneficiary version
	 */
	@AutoEscape
	public String getFatherName();

	/**
	 * Sets the father name of this ffp beneficiary version.
	 *
	 * @param fatherName the father name of this ffp beneficiary version
	 */
	public void setFatherName(String fatherName);

	/**
	 * Returns the mother name of this ffp beneficiary version.
	 *
	 * @return the mother name of this ffp beneficiary version
	 */
	@AutoEscape
	public String getMotherName();

	/**
	 * Sets the mother name of this ffp beneficiary version.
	 *
	 * @param motherName the mother name of this ffp beneficiary version
	 */
	public void setMotherName(String motherName);

	/**
	 * Returns the marital status of this ffp beneficiary version.
	 *
	 * @return the marital status of this ffp beneficiary version
	 */
	public int getMaritalStatus();

	/**
	 * Sets the marital status of this ffp beneficiary version.
	 *
	 * @param maritalStatus the marital status of this ffp beneficiary version
	 */
	public void setMaritalStatus(int maritalStatus);

	/**
	 * Returns the spouse name of this ffp beneficiary version.
	 *
	 * @return the spouse name of this ffp beneficiary version
	 */
	@AutoEscape
	public String getSpouseName();

	/**
	 * Sets the spouse name of this ffp beneficiary version.
	 *
	 * @param spouseName the spouse name of this ffp beneficiary version
	 */
	public void setSpouseName(String spouseName);

	/**
	 * Returns the spouse father name of this ffp beneficiary version.
	 *
	 * @return the spouse father name of this ffp beneficiary version
	 */
	@AutoEscape
	public String getSpouseFatherName();

	/**
	 * Sets the spouse father name of this ffp beneficiary version.
	 *
	 * @param spouseFatherName the spouse father name of this ffp beneficiary version
	 */
	public void setSpouseFatherName(String spouseFatherName);

	/**
	 * Returns the spouse date of birth of this ffp beneficiary version.
	 *
	 * @return the spouse date of birth of this ffp beneficiary version
	 */
	public Date getSpouseDateOfBirth();

	/**
	 * Sets the spouse date of birth of this ffp beneficiary version.
	 *
	 * @param spouseDateOfBirth the spouse date of birth of this ffp beneficiary version
	 */
	public void setSpouseDateOfBirth(Date spouseDateOfBirth);

	/**
	 * Returns the spouse national ID of this ffp beneficiary version.
	 *
	 * @return the spouse national ID of this ffp beneficiary version
	 */
	public long getSpouseNationalId();

	/**
	 * Sets the spouse national ID of this ffp beneficiary version.
	 *
	 * @param spouseNationalId the spouse national ID of this ffp beneficiary version
	 */
	public void setSpouseNationalId(long spouseNationalId);

	/**
	 * Returns the family average monthly income of this ffp beneficiary version.
	 *
	 * @return the family average monthly income of this ffp beneficiary version
	 */
	@AutoEscape
	public String getFamilyAverageMonthlyIncome();

	/**
	 * Sets the family average monthly income of this ffp beneficiary version.
	 *
	 * @param familyAverageMonthlyIncome the family average monthly income of this ffp beneficiary version
	 */
	public void setFamilyAverageMonthlyIncome(
		String familyAverageMonthlyIncome);

	/**
	 * Returns the family earning members of this ffp beneficiary version.
	 *
	 * @return the family earning members of this ffp beneficiary version
	 */
	public int getFamilyEarningMembers();

	/**
	 * Sets the family earning members of this ffp beneficiary version.
	 *
	 * @param familyEarningMembers the family earning members of this ffp beneficiary version
	 */
	public void setFamilyEarningMembers(int familyEarningMembers);

	/**
	 * Returns the acknowledge of this ffp beneficiary version.
	 *
	 * @return the acknowledge of this ffp beneficiary version
	 */
	public boolean getAcknowledge();

	/**
	 * Returns <code>true</code> if this ffp beneficiary version is acknowledge.
	 *
	 * @return <code>true</code> if this ffp beneficiary version is acknowledge; <code>false</code> otherwise
	 */
	public boolean isAcknowledge();

	/**
	 * Sets whether this ffp beneficiary version is acknowledge.
	 *
	 * @param acknowledge the acknowledge of this ffp beneficiary version
	 */
	public void setAcknowledge(boolean acknowledge);

	/**
	 * Returns the non of my family members registered of this ffp beneficiary version.
	 *
	 * @return the non of my family members registered of this ffp beneficiary version
	 */
	public boolean getNonOfMyFamilyMembersRegistered();

	/**
	 * Returns <code>true</code> if this ffp beneficiary version is non of my family members registered.
	 *
	 * @return <code>true</code> if this ffp beneficiary version is non of my family members registered; <code>false</code> otherwise
	 */
	public boolean isNonOfMyFamilyMembersRegistered();

	/**
	 * Sets whether this ffp beneficiary version is non of my family members registered.
	 *
	 * @param nonOfMyFamilyMembersRegistered the non of my family members registered of this ffp beneficiary version
	 */
	public void setNonOfMyFamilyMembersRegistered(
		boolean nonOfMyFamilyMembersRegistered);

	/**
	 * Returns the status of this ffp beneficiary version.
	 *
	 * @return the status of this ffp beneficiary version
	 */
	public int getStatus();

	/**
	 * Sets the status of this ffp beneficiary version.
	 *
	 * @param status the status of this ffp beneficiary version
	 */
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this ffp beneficiary version.
	 *
	 * @return the status by user ID of this ffp beneficiary version
	 */
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this ffp beneficiary version.
	 *
	 * @param statusByUserId the status by user ID of this ffp beneficiary version
	 */
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this ffp beneficiary version.
	 *
	 * @return the status by user uuid of this ffp beneficiary version
	 */
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this ffp beneficiary version.
	 *
	 * @param statusByUserUuid the status by user uuid of this ffp beneficiary version
	 */
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status date of this ffp beneficiary version.
	 *
	 * @return the status date of this ffp beneficiary version
	 */
	public Date getStatusDate();

	/**
	 * Sets the status date of this ffp beneficiary version.
	 *
	 * @param statusDate the status date of this ffp beneficiary version
	 */
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the created by of this ffp beneficiary version.
	 *
	 * @return the created by of this ffp beneficiary version
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this ffp beneficiary version.
	 *
	 * @param createdBy the created by of this ffp beneficiary version
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the create date of this ffp beneficiary version.
	 *
	 * @return the create date of this ffp beneficiary version
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this ffp beneficiary version.
	 *
	 * @param createDate the create date of this ffp beneficiary version
	 */
	public void setCreateDate(Date createDate);

	@Override
	public FFPBeneficiaryVersion cloneWithOriginalValues();

}