info:
    description: "DgfoodHeadlessCreditOtherPriorityCustomer REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "DgfoodHeadlessCreditOtherPriorityCustomer"
    version: v1.0
openapi: 3.0.1
components:
    schemas:
        CreditOtherPriorityCustomerAccount:
            properties:
                id:
                    format: int64
                    readOnly: true
                    type: integer
                userType:
                    description:
                        Represents type of user.
                    enum: [credit, otherpriority]
                    type: string
                mobileNumber:
                    type: string
                emailAddress:
                    type: string
                title:
                    type: string
                contactPersonName:
                    type: string
                contactPersonDesignation:
                    type: string
                officeName:
                    type: string
                organizationName:
                    type: string
                organizationType:
                    type: string
                gender:
                    properties:
                        key:
                           type: integer
                        value:
                           readOnly: true
                           type: string
                    type: object
                officeAddress:
                    $ref: "#/components/schemas/Address"
                status:
                    properties:
                        key:
                           type: integer
                        value:
                           readOnly: true
                           type: string
                    type: object
            type: object
        Address:
            description: Represents the office contact information.
            properties:
                region:
                    $ref: "#/components/schemas/Location"
                district:
                    $ref: "#/components/schemas/Location"
                upazilla:
                    $ref: "#/components/schemas/Location"
                union:
                    $ref: "#/components/schemas/Location"
                ward:
                    $ref: "#/components/schemas/Location"
                postOffice:
                    type : string
                zipCode:
                    format: int64
                    type: integer
                village:
                    type: string
                address:
                    type: string
            type: object
        Location:
            description: 
            properties:
                 id:
                    format: int64
                    type: integer
                 value:
                    readOnly: true
                    type: string
            type: object            
paths:
    "/credit-other-priority-customer-accounts":
        get:
            description: Retrieves the credit or other priority customer. Results can be paginated, filtered, and searched.
            operationId: getCreditOtherPriorityCustomerAccountsPage
            parameters:
                - in: query
                  name: userType
                  required: true
                  schema:
                      type: string
                - in: query
                  name: filter
                  schema:
                      type: string
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: sort
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/CreditOtherPriorityCustomerAccount"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/CreditOtherPriorityCustomerAccount"
                                type: array
                    description: ""
            tags: ["CreditOtherPriorityCustomerAccount"]
        post:
            description: Creates a new credit or other priority customer
            operationId: postCreditOtherPriorityCustomerAccount
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/CreditOtherPriorityCustomerAccount"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/CreditOtherPriorityCustomerAccount"
            responses:
                201:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/CreditOtherPriorityCustomerAccount"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/CreditOtherPriorityCustomerAccount"
                    description: ""
            tags: ["CreditOtherPriorityCustomerAccount"]
    "/credit-other-priority-customer-accounts/{creditOtherPriorityCustomerAccountId}":
        get:
            description: Retrieves the credit or other priority customer details.
            operationId: getCreditOtherPriorityCustomerAccount
            parameters:
                - in: path
                  name: creditOtherPriorityCustomerAccountId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/CreditOtherPriorityCustomerAccount"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/CreditOtherPriorityCustomerAccount"
                    description: ""
            tags: ["CreditOtherPriorityCustomerAccount"]
        put:
            description:
                Update the credit or other priority customer details with information sent in the request body as a new version. Any missing fields are deleted
                unless they are required.
            operationId: putCreditOtherPriorityCustomerAccount
            parameters:
                - in: path
                  name: creditOtherPriorityCustomerAccountId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/CreditOtherPriorityCustomerAccount"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/CreditOtherPriorityCustomerAccount"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/CreditOtherPriorityCustomerAccount"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/CreditOtherPriorityCustomerAccount"
                    description: "credit or other priority customer details successfully updated"
            tags: ["CreditOtherPriorityCustomerAccount"]

