/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.common.services.model.impl;

import bd.gov.dgfood.common.services.model.Address;
import bd.gov.dgfood.common.services.model.AddressModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Address service. Represents a row in the &quot;DGF_Address&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AddressModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AddressImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AddressImpl
 * @generated
 */
@JSON(strict = true)
public class AddressModelImpl
	extends BaseModelImpl<Address> implements AddressModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a address model instance should use the <code>Address</code> interface instead.
	 */
	public static final String TABLE_NAME = "DGF_Address";

	public static final Object[][] TABLE_COLUMNS = {
		{"addressId", Types.BIGINT}, {"region", Types.BIGINT},
		{"district", Types.BIGINT}, {"upazilla", Types.BIGINT},
		{"cityCorporationOrMunicipality", Types.BIGINT},
		{"unionOrWard", Types.BIGINT}, {"zipCode", Types.BIGINT},
		{"postOffice", Types.VARCHAR}, {"villageOrRoad", Types.VARCHAR},
		{"mouzaOrMoholla", Types.VARCHAR}, {"address", Types.VARCHAR},
		{"addressType", Types.VARCHAR}, {"classPK", Types.BIGINT},
		{"className", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("addressId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("region", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("district", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("upazilla", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("cityCorporationOrMunicipality", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("unionOrWard", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("zipCode", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("postOffice", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("villageOrRoad", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mouzaOrMoholla", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("address", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("addressType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("className", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DGF_Address (addressId LONG not null primary key,region LONG,district LONG,upazilla LONG,cityCorporationOrMunicipality LONG,unionOrWard LONG,zipCode LONG,postOffice VARCHAR(75) null,villageOrRoad VARCHAR(75) null,mouzaOrMoholla VARCHAR(75) null,address VARCHAR(75) null,addressType VARCHAR(75) null,classPK LONG,className VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table DGF_Address";

	public static final String ORDER_BY_JPQL =
		" ORDER BY address.addressId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DGF_Address.addressId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ADDRESSTYPE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLASSNAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLASSPK_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ADDRESSID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AddressModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _addressId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAddressId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _addressId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Address.class;
	}

	@Override
	public String getModelClassName() {
		return Address.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Address, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Address, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Address, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Address)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Address, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Address, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Address)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Address, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Address, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Address, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Address, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Address, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Address, Object>>();
		Map<String, BiConsumer<Address, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Address, ?>>();

		attributeGetterFunctions.put("addressId", Address::getAddressId);
		attributeSetterBiConsumers.put(
			"addressId", (BiConsumer<Address, Long>)Address::setAddressId);
		attributeGetterFunctions.put("region", Address::getRegion);
		attributeSetterBiConsumers.put(
			"region", (BiConsumer<Address, Long>)Address::setRegion);
		attributeGetterFunctions.put("district", Address::getDistrict);
		attributeSetterBiConsumers.put(
			"district", (BiConsumer<Address, Long>)Address::setDistrict);
		attributeGetterFunctions.put("upazilla", Address::getUpazilla);
		attributeSetterBiConsumers.put(
			"upazilla", (BiConsumer<Address, Long>)Address::setUpazilla);
		attributeGetterFunctions.put(
			"cityCorporationOrMunicipality",
			Address::getCityCorporationOrMunicipality);
		attributeSetterBiConsumers.put(
			"cityCorporationOrMunicipality",
			(BiConsumer<Address, Long>)
				Address::setCityCorporationOrMunicipality);
		attributeGetterFunctions.put("unionOrWard", Address::getUnionOrWard);
		attributeSetterBiConsumers.put(
			"unionOrWard", (BiConsumer<Address, Long>)Address::setUnionOrWard);
		attributeGetterFunctions.put("zipCode", Address::getZipCode);
		attributeSetterBiConsumers.put(
			"zipCode", (BiConsumer<Address, Long>)Address::setZipCode);
		attributeGetterFunctions.put("postOffice", Address::getPostOffice);
		attributeSetterBiConsumers.put(
			"postOffice", (BiConsumer<Address, String>)Address::setPostOffice);
		attributeGetterFunctions.put(
			"villageOrRoad", Address::getVillageOrRoad);
		attributeSetterBiConsumers.put(
			"villageOrRoad",
			(BiConsumer<Address, String>)Address::setVillageOrRoad);
		attributeGetterFunctions.put(
			"mouzaOrMoholla", Address::getMouzaOrMoholla);
		attributeSetterBiConsumers.put(
			"mouzaOrMoholla",
			(BiConsumer<Address, String>)Address::setMouzaOrMoholla);
		attributeGetterFunctions.put("address", Address::getAddress);
		attributeSetterBiConsumers.put(
			"address", (BiConsumer<Address, String>)Address::setAddress);
		attributeGetterFunctions.put("addressType", Address::getAddressType);
		attributeSetterBiConsumers.put(
			"addressType",
			(BiConsumer<Address, String>)Address::setAddressType);
		attributeGetterFunctions.put("classPK", Address::getClassPK);
		attributeSetterBiConsumers.put(
			"classPK", (BiConsumer<Address, Long>)Address::setClassPK);
		attributeGetterFunctions.put("className", Address::getClassName);
		attributeSetterBiConsumers.put(
			"className", (BiConsumer<Address, String>)Address::setClassName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getAddressId() {
		return _addressId;
	}

	@Override
	public void setAddressId(long addressId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_addressId = addressId;
	}

	@JSON
	@Override
	public long getRegion() {
		return _region;
	}

	@Override
	public void setRegion(long region) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_region = region;
	}

	@JSON
	@Override
	public long getDistrict() {
		return _district;
	}

	@Override
	public void setDistrict(long district) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_district = district;
	}

	@JSON
	@Override
	public long getUpazilla() {
		return _upazilla;
	}

	@Override
	public void setUpazilla(long upazilla) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_upazilla = upazilla;
	}

	@JSON
	@Override
	public long getCityCorporationOrMunicipality() {
		return _cityCorporationOrMunicipality;
	}

	@Override
	public void setCityCorporationOrMunicipality(
		long cityCorporationOrMunicipality) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cityCorporationOrMunicipality = cityCorporationOrMunicipality;
	}

	@JSON
	@Override
	public long getUnionOrWard() {
		return _unionOrWard;
	}

	@Override
	public void setUnionOrWard(long unionOrWard) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_unionOrWard = unionOrWard;
	}

	@JSON
	@Override
	public long getZipCode() {
		return _zipCode;
	}

	@Override
	public void setZipCode(long zipCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_zipCode = zipCode;
	}

	@JSON
	@Override
	public String getPostOffice() {
		if (_postOffice == null) {
			return "";
		}
		else {
			return _postOffice;
		}
	}

	@Override
	public void setPostOffice(String postOffice) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_postOffice = postOffice;
	}

	@JSON
	@Override
	public String getVillageOrRoad() {
		if (_villageOrRoad == null) {
			return "";
		}
		else {
			return _villageOrRoad;
		}
	}

	@Override
	public void setVillageOrRoad(String villageOrRoad) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_villageOrRoad = villageOrRoad;
	}

	@JSON
	@Override
	public String getMouzaOrMoholla() {
		if (_mouzaOrMoholla == null) {
			return "";
		}
		else {
			return _mouzaOrMoholla;
		}
	}

	@Override
	public void setMouzaOrMoholla(String mouzaOrMoholla) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mouzaOrMoholla = mouzaOrMoholla;
	}

	@JSON
	@Override
	public String getAddress() {
		if (_address == null) {
			return "";
		}
		else {
			return _address;
		}
	}

	@Override
	public void setAddress(String address) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_address = address;
	}

	@JSON
	@Override
	public String getAddressType() {
		if (_addressType == null) {
			return "";
		}
		else {
			return _addressType;
		}
	}

	@Override
	public void setAddressType(String addressType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_addressType = addressType;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalAddressType() {
		return getColumnOriginalValue("addressType");
	}

	@JSON
	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classPK = classPK;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalClassPK() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("classPK"));
	}

	@JSON
	@Override
	public String getClassName() {
		if (_className == null) {
			return "";
		}
		else {
			return _className;
		}
	}

	@Override
	public void setClassName(String className) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_className = className;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalClassName() {
		return getColumnOriginalValue("className");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Address.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Address toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Address>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AddressImpl addressImpl = new AddressImpl();

		addressImpl.setAddressId(getAddressId());
		addressImpl.setRegion(getRegion());
		addressImpl.setDistrict(getDistrict());
		addressImpl.setUpazilla(getUpazilla());
		addressImpl.setCityCorporationOrMunicipality(
			getCityCorporationOrMunicipality());
		addressImpl.setUnionOrWard(getUnionOrWard());
		addressImpl.setZipCode(getZipCode());
		addressImpl.setPostOffice(getPostOffice());
		addressImpl.setVillageOrRoad(getVillageOrRoad());
		addressImpl.setMouzaOrMoholla(getMouzaOrMoholla());
		addressImpl.setAddress(getAddress());
		addressImpl.setAddressType(getAddressType());
		addressImpl.setClassPK(getClassPK());
		addressImpl.setClassName(getClassName());

		addressImpl.resetOriginalValues();

		return addressImpl;
	}

	@Override
	public Address cloneWithOriginalValues() {
		AddressImpl addressImpl = new AddressImpl();

		addressImpl.setAddressId(
			this.<Long>getColumnOriginalValue("addressId"));
		addressImpl.setRegion(this.<Long>getColumnOriginalValue("region"));
		addressImpl.setDistrict(this.<Long>getColumnOriginalValue("district"));
		addressImpl.setUpazilla(this.<Long>getColumnOriginalValue("upazilla"));
		addressImpl.setCityCorporationOrMunicipality(
			this.<Long>getColumnOriginalValue("cityCorporationOrMunicipality"));
		addressImpl.setUnionOrWard(
			this.<Long>getColumnOriginalValue("unionOrWard"));
		addressImpl.setZipCode(this.<Long>getColumnOriginalValue("zipCode"));
		addressImpl.setPostOffice(
			this.<String>getColumnOriginalValue("postOffice"));
		addressImpl.setVillageOrRoad(
			this.<String>getColumnOriginalValue("villageOrRoad"));
		addressImpl.setMouzaOrMoholla(
			this.<String>getColumnOriginalValue("mouzaOrMoholla"));
		addressImpl.setAddress(this.<String>getColumnOriginalValue("address"));
		addressImpl.setAddressType(
			this.<String>getColumnOriginalValue("addressType"));
		addressImpl.setClassPK(this.<Long>getColumnOriginalValue("classPK"));
		addressImpl.setClassName(
			this.<String>getColumnOriginalValue("className"));

		return addressImpl;
	}

	@Override
	public int compareTo(Address address) {
		long primaryKey = address.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Address)) {
			return false;
		}

		Address address = (Address)object;

		long primaryKey = address.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Address> toCacheModel() {
		AddressCacheModel addressCacheModel = new AddressCacheModel();

		addressCacheModel.addressId = getAddressId();

		addressCacheModel.region = getRegion();

		addressCacheModel.district = getDistrict();

		addressCacheModel.upazilla = getUpazilla();

		addressCacheModel.cityCorporationOrMunicipality =
			getCityCorporationOrMunicipality();

		addressCacheModel.unionOrWard = getUnionOrWard();

		addressCacheModel.zipCode = getZipCode();

		addressCacheModel.postOffice = getPostOffice();

		String postOffice = addressCacheModel.postOffice;

		if ((postOffice != null) && (postOffice.length() == 0)) {
			addressCacheModel.postOffice = null;
		}

		addressCacheModel.villageOrRoad = getVillageOrRoad();

		String villageOrRoad = addressCacheModel.villageOrRoad;

		if ((villageOrRoad != null) && (villageOrRoad.length() == 0)) {
			addressCacheModel.villageOrRoad = null;
		}

		addressCacheModel.mouzaOrMoholla = getMouzaOrMoholla();

		String mouzaOrMoholla = addressCacheModel.mouzaOrMoholla;

		if ((mouzaOrMoholla != null) && (mouzaOrMoholla.length() == 0)) {
			addressCacheModel.mouzaOrMoholla = null;
		}

		addressCacheModel.address = getAddress();

		String address = addressCacheModel.address;

		if ((address != null) && (address.length() == 0)) {
			addressCacheModel.address = null;
		}

		addressCacheModel.addressType = getAddressType();

		String addressType = addressCacheModel.addressType;

		if ((addressType != null) && (addressType.length() == 0)) {
			addressCacheModel.addressType = null;
		}

		addressCacheModel.classPK = getClassPK();

		addressCacheModel.className = getClassName();

		String className = addressCacheModel.className;

		if ((className != null) && (className.length() == 0)) {
			addressCacheModel.className = null;
		}

		return addressCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Address, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Address, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Address, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Address)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Address, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Address, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Address, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Address)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Address>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Address.class, ModelWrapper.class);

	}

	private long _addressId;
	private long _region;
	private long _district;
	private long _upazilla;
	private long _cityCorporationOrMunicipality;
	private long _unionOrWard;
	private long _zipCode;
	private String _postOffice;
	private String _villageOrRoad;
	private String _mouzaOrMoholla;
	private String _address;
	private String _addressType;
	private long _classPK;
	private String _className;

	public <T> T getColumnValue(String columnName) {
		Function<Address, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Address)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("addressId", _addressId);
		_columnOriginalValues.put("region", _region);
		_columnOriginalValues.put("district", _district);
		_columnOriginalValues.put("upazilla", _upazilla);
		_columnOriginalValues.put(
			"cityCorporationOrMunicipality", _cityCorporationOrMunicipality);
		_columnOriginalValues.put("unionOrWard", _unionOrWard);
		_columnOriginalValues.put("zipCode", _zipCode);
		_columnOriginalValues.put("postOffice", _postOffice);
		_columnOriginalValues.put("villageOrRoad", _villageOrRoad);
		_columnOriginalValues.put("mouzaOrMoholla", _mouzaOrMoholla);
		_columnOriginalValues.put("address", _address);
		_columnOriginalValues.put("addressType", _addressType);
		_columnOriginalValues.put("classPK", _classPK);
		_columnOriginalValues.put("className", _className);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("addressId", 1L);

		columnBitmasks.put("region", 2L);

		columnBitmasks.put("district", 4L);

		columnBitmasks.put("upazilla", 8L);

		columnBitmasks.put("cityCorporationOrMunicipality", 16L);

		columnBitmasks.put("unionOrWard", 32L);

		columnBitmasks.put("zipCode", 64L);

		columnBitmasks.put("postOffice", 128L);

		columnBitmasks.put("villageOrRoad", 256L);

		columnBitmasks.put("mouzaOrMoholla", 512L);

		columnBitmasks.put("address", 1024L);

		columnBitmasks.put("addressType", 2048L);

		columnBitmasks.put("classPK", 4096L);

		columnBitmasks.put("className", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Address _escapedModel;

}