/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.common.services.model.impl;

import bd.gov.dgfood.common.services.model.UserLocation;
import bd.gov.dgfood.common.services.model.UserLocationModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the UserLocation service. Represents a row in the &quot;DGF_UserLocation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>UserLocationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserLocationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserLocationImpl
 * @generated
 */
@JSON(strict = true)
public class UserLocationModelImpl
	extends BaseModelImpl<UserLocation> implements UserLocationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user location model instance should use the <code>UserLocation</code> interface instead.
	 */
	public static final String TABLE_NAME = "DGF_UserLocation";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"userLocationId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"locationName", Types.VARCHAR}, {"locationCode", Types.VARCHAR},
		{"locationId", Types.BIGINT}, {"locationType", Types.VARCHAR},
		{"userName", Types.VARCHAR}, {"userId", Types.BIGINT},
		{"roleKey", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"createdBy", Types.BIGINT},
		{"modifiedBy", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userLocationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("locationName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("locationCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("locationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("locationType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("roleKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DGF_UserLocation (uuid_ VARCHAR(75) null,userLocationId LONG not null primary key,companyId LONG,groupId LONG,locationName VARCHAR(75) null,locationCode VARCHAR(75) null,locationId LONG,locationType VARCHAR(75) null,userName VARCHAR(75) null,userId LONG,roleKey VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,createdBy LONG,modifiedBy LONG)";

	public static final String TABLE_SQL_DROP = "drop table DGF_UserLocation";

	public static final String ORDER_BY_JPQL =
		" ORDER BY userLocation.userLocationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DGF_UserLocation.userLocationId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOCATIONCODE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOCATIONID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ROLEKEY_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERLOCATIONID_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public UserLocationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _userLocationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setUserLocationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _userLocationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UserLocation.class;
	}

	@Override
	public String getModelClassName() {
		return UserLocation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<UserLocation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<UserLocation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserLocation, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((UserLocation)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<UserLocation, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<UserLocation, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(UserLocation)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<UserLocation, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<UserLocation, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<UserLocation, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<UserLocation, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<UserLocation, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<UserLocation, Object>>();
		Map<String, BiConsumer<UserLocation, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<UserLocation, ?>>();

		attributeGetterFunctions.put("uuid", UserLocation::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<UserLocation, String>)UserLocation::setUuid);
		attributeGetterFunctions.put(
			"userLocationId", UserLocation::getUserLocationId);
		attributeSetterBiConsumers.put(
			"userLocationId",
			(BiConsumer<UserLocation, Long>)UserLocation::setUserLocationId);
		attributeGetterFunctions.put("companyId", UserLocation::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<UserLocation, Long>)UserLocation::setCompanyId);
		attributeGetterFunctions.put("groupId", UserLocation::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<UserLocation, Long>)UserLocation::setGroupId);
		attributeGetterFunctions.put(
			"locationName", UserLocation::getLocationName);
		attributeSetterBiConsumers.put(
			"locationName",
			(BiConsumer<UserLocation, String>)UserLocation::setLocationName);
		attributeGetterFunctions.put(
			"locationCode", UserLocation::getLocationCode);
		attributeSetterBiConsumers.put(
			"locationCode",
			(BiConsumer<UserLocation, String>)UserLocation::setLocationCode);
		attributeGetterFunctions.put("locationId", UserLocation::getLocationId);
		attributeSetterBiConsumers.put(
			"locationId",
			(BiConsumer<UserLocation, Long>)UserLocation::setLocationId);
		attributeGetterFunctions.put(
			"locationType", UserLocation::getLocationType);
		attributeSetterBiConsumers.put(
			"locationType",
			(BiConsumer<UserLocation, String>)UserLocation::setLocationType);
		attributeGetterFunctions.put("userName", UserLocation::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<UserLocation, String>)UserLocation::setUserName);
		attributeGetterFunctions.put("userId", UserLocation::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<UserLocation, Long>)UserLocation::setUserId);
		attributeGetterFunctions.put("roleKey", UserLocation::getRoleKey);
		attributeSetterBiConsumers.put(
			"roleKey",
			(BiConsumer<UserLocation, String>)UserLocation::setRoleKey);
		attributeGetterFunctions.put("createDate", UserLocation::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<UserLocation, Date>)UserLocation::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", UserLocation::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<UserLocation, Date>)UserLocation::setModifiedDate);
		attributeGetterFunctions.put("createdBy", UserLocation::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<UserLocation, Long>)UserLocation::setCreatedBy);
		attributeGetterFunctions.put("modifiedBy", UserLocation::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<UserLocation, Long>)UserLocation::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getUserLocationId() {
		return _userLocationId;
	}

	@Override
	public void setUserLocationId(long userLocationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userLocationId = userLocationId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public String getLocationName() {
		if (_locationName == null) {
			return "";
		}
		else {
			return _locationName;
		}
	}

	@Override
	public void setLocationName(String locationName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_locationName = locationName;
	}

	@JSON
	@Override
	public String getLocationCode() {
		if (_locationCode == null) {
			return "";
		}
		else {
			return _locationCode;
		}
	}

	@Override
	public void setLocationCode(String locationCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_locationCode = locationCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLocationCode() {
		return getColumnOriginalValue("locationCode");
	}

	@JSON
	@Override
	public long getLocationId() {
		return _locationId;
	}

	@Override
	public void setLocationId(long locationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_locationId = locationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalLocationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("locationId"));
	}

	@JSON
	@Override
	public String getLocationType() {
		if (_locationType == null) {
			return "";
		}
		else {
			return _locationType;
		}
	}

	@Override
	public void setLocationType(String locationType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_locationType = locationType;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public String getRoleKey() {
		if (_roleKey == null) {
			return "";
		}
		else {
			return _roleKey;
		}
	}

	@Override
	public void setRoleKey(String roleKey) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_roleKey = roleKey;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalRoleKey() {
		return getColumnOriginalValue("roleKey");
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(UserLocation.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), UserLocation.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UserLocation toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, UserLocation>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UserLocationImpl userLocationImpl = new UserLocationImpl();

		userLocationImpl.setUuid(getUuid());
		userLocationImpl.setUserLocationId(getUserLocationId());
		userLocationImpl.setCompanyId(getCompanyId());
		userLocationImpl.setGroupId(getGroupId());
		userLocationImpl.setLocationName(getLocationName());
		userLocationImpl.setLocationCode(getLocationCode());
		userLocationImpl.setLocationId(getLocationId());
		userLocationImpl.setLocationType(getLocationType());
		userLocationImpl.setUserName(getUserName());
		userLocationImpl.setUserId(getUserId());
		userLocationImpl.setRoleKey(getRoleKey());
		userLocationImpl.setCreateDate(getCreateDate());
		userLocationImpl.setModifiedDate(getModifiedDate());
		userLocationImpl.setCreatedBy(getCreatedBy());
		userLocationImpl.setModifiedBy(getModifiedBy());

		userLocationImpl.resetOriginalValues();

		return userLocationImpl;
	}

	@Override
	public UserLocation cloneWithOriginalValues() {
		UserLocationImpl userLocationImpl = new UserLocationImpl();

		userLocationImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		userLocationImpl.setUserLocationId(
			this.<Long>getColumnOriginalValue("userLocationId"));
		userLocationImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		userLocationImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		userLocationImpl.setLocationName(
			this.<String>getColumnOriginalValue("locationName"));
		userLocationImpl.setLocationCode(
			this.<String>getColumnOriginalValue("locationCode"));
		userLocationImpl.setLocationId(
			this.<Long>getColumnOriginalValue("locationId"));
		userLocationImpl.setLocationType(
			this.<String>getColumnOriginalValue("locationType"));
		userLocationImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		userLocationImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		userLocationImpl.setRoleKey(
			this.<String>getColumnOriginalValue("roleKey"));
		userLocationImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		userLocationImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		userLocationImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		userLocationImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));

		return userLocationImpl;
	}

	@Override
	public int compareTo(UserLocation userLocation) {
		long primaryKey = userLocation.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof UserLocation)) {
			return false;
		}

		UserLocation userLocation = (UserLocation)object;

		long primaryKey = userLocation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<UserLocation> toCacheModel() {
		UserLocationCacheModel userLocationCacheModel =
			new UserLocationCacheModel();

		userLocationCacheModel.uuid = getUuid();

		String uuid = userLocationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			userLocationCacheModel.uuid = null;
		}

		userLocationCacheModel.userLocationId = getUserLocationId();

		userLocationCacheModel.companyId = getCompanyId();

		userLocationCacheModel.groupId = getGroupId();

		userLocationCacheModel.locationName = getLocationName();

		String locationName = userLocationCacheModel.locationName;

		if ((locationName != null) && (locationName.length() == 0)) {
			userLocationCacheModel.locationName = null;
		}

		userLocationCacheModel.locationCode = getLocationCode();

		String locationCode = userLocationCacheModel.locationCode;

		if ((locationCode != null) && (locationCode.length() == 0)) {
			userLocationCacheModel.locationCode = null;
		}

		userLocationCacheModel.locationId = getLocationId();

		userLocationCacheModel.locationType = getLocationType();

		String locationType = userLocationCacheModel.locationType;

		if ((locationType != null) && (locationType.length() == 0)) {
			userLocationCacheModel.locationType = null;
		}

		userLocationCacheModel.userName = getUserName();

		String userName = userLocationCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			userLocationCacheModel.userName = null;
		}

		userLocationCacheModel.userId = getUserId();

		userLocationCacheModel.roleKey = getRoleKey();

		String roleKey = userLocationCacheModel.roleKey;

		if ((roleKey != null) && (roleKey.length() == 0)) {
			userLocationCacheModel.roleKey = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			userLocationCacheModel.createDate = createDate.getTime();
		}
		else {
			userLocationCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			userLocationCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			userLocationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		userLocationCacheModel.createdBy = getCreatedBy();

		userLocationCacheModel.modifiedBy = getModifiedBy();

		return userLocationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<UserLocation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<UserLocation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserLocation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((UserLocation)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<UserLocation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<UserLocation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserLocation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((UserLocation)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, UserLocation>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					UserLocation.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _userLocationId;
	private long _companyId;
	private long _groupId;
	private String _locationName;
	private String _locationCode;
	private long _locationId;
	private String _locationType;
	private String _userName;
	private long _userId;
	private String _roleKey;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _createdBy;
	private long _modifiedBy;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<UserLocation, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((UserLocation)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("userLocationId", _userLocationId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("locationName", _locationName);
		_columnOriginalValues.put("locationCode", _locationCode);
		_columnOriginalValues.put("locationId", _locationId);
		_columnOriginalValues.put("locationType", _locationType);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("roleKey", _roleKey);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("userLocationId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("locationName", 16L);

		columnBitmasks.put("locationCode", 32L);

		columnBitmasks.put("locationId", 64L);

		columnBitmasks.put("locationType", 128L);

		columnBitmasks.put("userName", 256L);

		columnBitmasks.put("userId", 512L);

		columnBitmasks.put("roleKey", 1024L);

		columnBitmasks.put("createDate", 2048L);

		columnBitmasks.put("modifiedDate", 4096L);

		columnBitmasks.put("createdBy", 8192L);

		columnBitmasks.put("modifiedBy", 16384L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private UserLocation _escapedModel;

}