create table DGFOOD_SalesCustomer (
	uuid_ VARCHAR(75) null,
	salesCustomerId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	createdBy LONG,
	createDate DATE null,
	modifiedBy LONG,
	modifiedDate DATE null,
	userId LONG,
	userType VARCHAR(75) null,
	mobileNumber VARCHAR(75) null,
	emailAddress VARCHAR(75) null,
	title VARCHAR(75) null,
	contactPersonName VARCHAR(75) null,
	contactPersonDesignation VARCHAR(75) null,
	officeName VARCHAR(75) null,
	organizationName VARCHAR(75) null,
	organizationType VARCHAR(75) null,
	gender INTEGER,
	salesCustomerCode LONG,
	version DOUBLE,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);

create table DGFOOD_SalesCustomerAllocation (
	uuid_ VARCHAR(75) null,
	salesCustomerAllocationId LONG not null primary key,
	salesCustomerCode LONG,
	salesCustomerName VARCHAR(75) null,
	allocationNumber LONG,
	salesOrganization VARCHAR(75) null,
	distributionChannel VARCHAR(75) null,
	year INTEGER,
	district VARCHAR(75) null,
	subDistrict VARCHAR(75) null,
	govOrderNumber VARCHAR(75) null,
	commodity VARCHAR(75) null,
	yearlyQty DOUBLE,
	yearlyQtyUnit VARCHAR(75) null,
	monthlyQty DOUBLE,
	monthlyQtyUnit VARCHAR(75) null,
	companyId LONG,
	createDate DATE null,
	modifiedDate DATE null
);

create table DGFOOD_SalesCustomerVersion (
	uuid_ VARCHAR(75) null,
	salesCustomerVersionId LONG not null primary key,
	salesCustomerId LONG,
	groupId LONG,
	companyId LONG,
	createdBy LONG,
	createDate DATE null,
	modifiedBy LONG,
	modifiedDate DATE null,
	userId LONG,
	userType VARCHAR(75) null,
	mobileNumber VARCHAR(75) null,
	emailAddress VARCHAR(75) null,
	title VARCHAR(75) null,
	contactPersonName VARCHAR(75) null,
	contactPersonDesignation VARCHAR(75) null,
	officeName VARCHAR(75) null,
	organizationName VARCHAR(75) null,
	organizationType VARCHAR(75) null,
	gender INTEGER,
	version DOUBLE,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);