/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.farmer.information.management.system.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.io.Serializable;

import java.util.Date;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FarmerRegistration service. Represents a row in the &quot;DGFood_FarmerRegistration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>bd.gov.dgfood.farmer.information.management.system.model.impl.FarmerRegistrationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>bd.gov.dgfood.farmer.information.management.system.model.impl.FarmerRegistrationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FarmerRegistration
 * @generated
 */
@ProviderType
public interface FarmerRegistrationModel
	extends BaseModel<FarmerRegistration>, ShardedModel, StagedModel,
			WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a farmer registration model instance should use the {@link FarmerRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this farmer registration.
	 *
	 * @return the primary key of this farmer registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this farmer registration.
	 *
	 * @param primaryKey the primary key of this farmer registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this farmer registration.
	 *
	 * @return the uuid of this farmer registration
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this farmer registration.
	 *
	 * @param uuid the uuid of this farmer registration
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the farmer registration ID of this farmer registration.
	 *
	 * @return the farmer registration ID of this farmer registration
	 */
	public long getFarmerRegistrationId();

	/**
	 * Sets the farmer registration ID of this farmer registration.
	 *
	 * @param farmerRegistrationId the farmer registration ID of this farmer registration
	 */
	public void setFarmerRegistrationId(long farmerRegistrationId);

	/**
	 * Returns the application number of this farmer registration.
	 *
	 * @return the application number of this farmer registration
	 */
	@AutoEscape
	public String getApplicationNumber();

	/**
	 * Sets the application number of this farmer registration.
	 *
	 * @param applicationNumber the application number of this farmer registration
	 */
	public void setApplicationNumber(String applicationNumber);

	/**
	 * Returns the national ID of this farmer registration.
	 *
	 * @return the national ID of this farmer registration
	 */
	@AutoEscape
	public String getNationalId();

	/**
	 * Sets the national ID of this farmer registration.
	 *
	 * @param nationalId the national ID of this farmer registration
	 */
	public void setNationalId(String nationalId);

	/**
	 * Returns the email address of this farmer registration.
	 *
	 * @return the email address of this farmer registration
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this farmer registration.
	 *
	 * @param emailAddress the email address of this farmer registration
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the mobile number of this farmer registration.
	 *
	 * @return the mobile number of this farmer registration
	 */
	@AutoEscape
	public String getMobileNumber();

	/**
	 * Sets the mobile number of this farmer registration.
	 *
	 * @param mobileNumber the mobile number of this farmer registration
	 */
	public void setMobileNumber(String mobileNumber);

	/**
	 * Returns the date of birth of this farmer registration.
	 *
	 * @return the date of birth of this farmer registration
	 */
	public Date getDateOfBirth();

	/**
	 * Sets the date of birth of this farmer registration.
	 *
	 * @param dateOfBirth the date of birth of this farmer registration
	 */
	public void setDateOfBirth(Date dateOfBirth);

	/**
	 * Returns the farmer name of this farmer registration.
	 *
	 * @return the farmer name of this farmer registration
	 */
	@AutoEscape
	public String getFarmerName();

	/**
	 * Sets the farmer name of this farmer registration.
	 *
	 * @param farmerName the farmer name of this farmer registration
	 */
	public void setFarmerName(String farmerName);

	/**
	 * Returns the father name of this farmer registration.
	 *
	 * @return the father name of this farmer registration
	 */
	@AutoEscape
	public String getFatherName();

	/**
	 * Sets the father name of this farmer registration.
	 *
	 * @param fatherName the father name of this farmer registration
	 */
	public void setFatherName(String fatherName);

	/**
	 * Returns the mother name of this farmer registration.
	 *
	 * @return the mother name of this farmer registration
	 */
	@AutoEscape
	public String getMotherName();

	/**
	 * Sets the mother name of this farmer registration.
	 *
	 * @param motherName the mother name of this farmer registration
	 */
	public void setMotherName(String motherName);

	/**
	 * Returns the gender of this farmer registration.
	 *
	 * @return the gender of this farmer registration
	 */
	public int getGender();

	/**
	 * Sets the gender of this farmer registration.
	 *
	 * @param gender the gender of this farmer registration
	 */
	public void setGender(int gender);

	/**
	 * Returns the marital status of this farmer registration.
	 *
	 * @return the marital status of this farmer registration
	 */
	public int getMaritalStatus();

	/**
	 * Sets the marital status of this farmer registration.
	 *
	 * @param maritalStatus the marital status of this farmer registration
	 */
	public void setMaritalStatus(int maritalStatus);

	/**
	 * Returns the krishok card number of this farmer registration.
	 *
	 * @return the krishok card number of this farmer registration
	 */
	@AutoEscape
	public String getKrishokCardNumber();

	/**
	 * Sets the krishok card number of this farmer registration.
	 *
	 * @param krishokCardNumber the krishok card number of this farmer registration
	 */
	public void setKrishokCardNumber(String krishokCardNumber);

	/**
	 * Returns the cultivable land season1 of this farmer registration.
	 *
	 * @return the cultivable land season1 of this farmer registration
	 */
	public Map<String, Serializable> getCultivableLandSeason1();

	/**
	 * Sets the cultivable land season1 of this farmer registration.
	 *
	 * @param cultivableLandSeason1 the cultivable land season1 of this farmer registration
	 */
	public void setCultivableLandSeason1(
		Map<String, Serializable> cultivableLandSeason1);

	/**
	 * Returns the cultivable land season2 of this farmer registration.
	 *
	 * @return the cultivable land season2 of this farmer registration
	 */
	public Map<String, Serializable> getCultivableLandSeason2();

	/**
	 * Sets the cultivable land season2 of this farmer registration.
	 *
	 * @param cultivableLandSeason2 the cultivable land season2 of this farmer registration
	 */
	public void setCultivableLandSeason2(
		Map<String, Serializable> cultivableLandSeason2);

	/**
	 * Returns the cultivable land season3 of this farmer registration.
	 *
	 * @return the cultivable land season3 of this farmer registration
	 */
	public Map<String, Serializable> getCultivableLandSeason3();

	/**
	 * Sets the cultivable land season3 of this farmer registration.
	 *
	 * @param cultivableLandSeason3 the cultivable land season3 of this farmer registration
	 */
	public void setCultivableLandSeason3(
		Map<String, Serializable> cultivableLandSeason3);

	/**
	 * Returns the farmer category of this farmer registration.
	 *
	 * @return the farmer category of this farmer registration
	 */
	@AutoEscape
	public String getFarmerCategory();

	/**
	 * Sets the farmer category of this farmer registration.
	 *
	 * @param farmerCategory  the farmer category of this farmer registration
	 */
	public void setFarmerCategory(String farmerCategory);

	/**
	 * Returns the password of this farmer registration.
	 *
	 * @return the password of this farmer registration
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this farmer registration.
	 *
	 * @param password  the password of this farmer registration
	 */
	public void setPassword(String password);

	/**
	 * Returns the remarks of this farmer registration.
	 *
	 * @return the remarks of this farmer registration
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this farmer registration.
	 *
	 * @param remarks the remarks of this farmer registration
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the business code of this farmer registration.
	 *
	 * @return the business code of this farmer registration
	 */
	@AutoEscape
	public String getBusinessCode();

	/**
	 * Sets the business code of this farmer registration.
	 *
	 * @param businessCode the business code of this farmer registration
	 */
	public void setBusinessCode(String businessCode);

	/**
	 * Returns the version of this farmer registration.
	 *
	 * @return the version of this farmer registration
	 */
	public double getVersion();

	/**
	 * Sets the version of this farmer registration.
	 *
	 * @param version the version of this farmer registration
	 */
	public void setVersion(double version);

	/**
	 * Returns the user ID of this farmer registration.
	 *
	 * @return the user ID of this farmer registration
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this farmer registration.
	 *
	 * @param userId the user ID of this farmer registration
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this farmer registration.
	 *
	 * @return the user uuid of this farmer registration
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this farmer registration.
	 *
	 * @param userUuid the user uuid of this farmer registration
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this farmer registration.
	 *
	 * @return the group ID of this farmer registration
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this farmer registration.
	 *
	 * @param groupId the group ID of this farmer registration
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this farmer registration.
	 *
	 * @return the company ID of this farmer registration
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this farmer registration.
	 *
	 * @param companyId the company ID of this farmer registration
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this farmer registration.
	 *
	 * @return the create date of this farmer registration
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this farmer registration.
	 *
	 * @param createDate the create date of this farmer registration
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this farmer registration.
	 *
	 * @return the modified date of this farmer registration
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this farmer registration.
	 *
	 * @param modifiedDate the modified date of this farmer registration
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the created by of this farmer registration.
	 *
	 * @return the created by of this farmer registration
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this farmer registration.
	 *
	 * @param createdBy the created by of this farmer registration
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this farmer registration.
	 *
	 * @return the modified by of this farmer registration
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this farmer registration.
	 *
	 * @param modifiedBy the modified by of this farmer registration
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the status of this farmer registration.
	 *
	 * @return the status of this farmer registration
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this farmer registration.
	 *
	 * @param status the status of this farmer registration
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this farmer registration.
	 *
	 * @return the status by user ID of this farmer registration
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this farmer registration.
	 *
	 * @param statusByUserId the status by user ID of this farmer registration
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this farmer registration.
	 *
	 * @return the status by user uuid of this farmer registration
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this farmer registration.
	 *
	 * @param statusByUserUuid the status by user uuid of this farmer registration
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this farmer registration.
	 *
	 * @return the status by user name of this farmer registration
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this farmer registration.
	 *
	 * @param statusByUserName the status by user name of this farmer registration
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this farmer registration.
	 *
	 * @return the status date of this farmer registration
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this farmer registration.
	 *
	 * @param statusDate the status date of this farmer registration
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this farmer registration is approved.
	 *
	 * @return <code>true</code> if this farmer registration is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this farmer registration is denied.
	 *
	 * @return <code>true</code> if this farmer registration is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this farmer registration is a draft.
	 *
	 * @return <code>true</code> if this farmer registration is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this farmer registration is expired.
	 *
	 * @return <code>true</code> if this farmer registration is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this farmer registration is inactive.
	 *
	 * @return <code>true</code> if this farmer registration is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this farmer registration is incomplete.
	 *
	 * @return <code>true</code> if this farmer registration is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this farmer registration is pending.
	 *
	 * @return <code>true</code> if this farmer registration is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this farmer registration is scheduled.
	 *
	 * @return <code>true</code> if this farmer registration is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public FarmerRegistration cloneWithOriginalValues();

}