/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.common.services.service.base;

import bd.gov.dgfood.common.services.model.BankAccountInformation;
import bd.gov.dgfood.common.services.service.BankAccountInformationLocalService;
import bd.gov.dgfood.common.services.service.BankAccountInformationLocalServiceUtil;
import bd.gov.dgfood.common.services.service.persistence.APIAuditPersistence;
import bd.gov.dgfood.common.services.service.persistence.AddressPersistence;
import bd.gov.dgfood.common.services.service.persistence.AddressVersionPersistence;
import bd.gov.dgfood.common.services.service.persistence.AttachmentPersistence;
import bd.gov.dgfood.common.services.service.persistence.AttachmentVersionPersistence;
import bd.gov.dgfood.common.services.service.persistence.BankAccountInformationPersistence;
import bd.gov.dgfood.common.services.service.persistence.DGFUsersPersistence;
import bd.gov.dgfood.common.services.service.persistence.DeliveryOrderPersistence;
import bd.gov.dgfood.common.services.service.persistence.GrievancePersistence;
import bd.gov.dgfood.common.services.service.persistence.IndentPersistence;
import bd.gov.dgfood.common.services.service.persistence.MDMSyncStatusPersistence;
import bd.gov.dgfood.common.services.service.persistence.UserDetailsPersistence;
import bd.gov.dgfood.common.services.service.persistence.UserLocationPersistence;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the bank account information local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link bd.gov.dgfood.common.services.service.impl.BankAccountInformationLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see bd.gov.dgfood.common.services.service.impl.BankAccountInformationLocalServiceImpl
 * @generated
 */
public abstract class BankAccountInformationLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, BankAccountInformationLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>BankAccountInformationLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>BankAccountInformationLocalServiceUtil</code>.
	 */

	/**
	 * Adds the bank account information to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect BankAccountInformationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param bankAccountInformation the bank account information
	 * @return the bank account information that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public BankAccountInformation addBankAccountInformation(
		BankAccountInformation bankAccountInformation) {

		bankAccountInformation.setNew(true);

		return bankAccountInformationPersistence.update(bankAccountInformation);
	}

	/**
	 * Creates a new bank account information with the primary key. Does not add the bank account information to the database.
	 *
	 * @param bankAccountInformationId the primary key for the new bank account information
	 * @return the new bank account information
	 */
	@Override
	@Transactional(enabled = false)
	public BankAccountInformation createBankAccountInformation(
		long bankAccountInformationId) {

		return bankAccountInformationPersistence.create(
			bankAccountInformationId);
	}

	/**
	 * Deletes the bank account information with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect BankAccountInformationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param bankAccountInformationId the primary key of the bank account information
	 * @return the bank account information that was removed
	 * @throws PortalException if a bank account information with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public BankAccountInformation deleteBankAccountInformation(
			long bankAccountInformationId)
		throws PortalException {

		return bankAccountInformationPersistence.remove(
			bankAccountInformationId);
	}

	/**
	 * Deletes the bank account information from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect BankAccountInformationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param bankAccountInformation the bank account information
	 * @return the bank account information that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public BankAccountInformation deleteBankAccountInformation(
		BankAccountInformation bankAccountInformation) {

		return bankAccountInformationPersistence.remove(bankAccountInformation);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return bankAccountInformationPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			BankAccountInformation.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return bankAccountInformationPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>bd.gov.dgfood.common.services.model.impl.BankAccountInformationModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return bankAccountInformationPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>bd.gov.dgfood.common.services.model.impl.BankAccountInformationModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return bankAccountInformationPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return bankAccountInformationPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return bankAccountInformationPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public BankAccountInformation fetchBankAccountInformation(
		long bankAccountInformationId) {

		return bankAccountInformationPersistence.fetchByPrimaryKey(
			bankAccountInformationId);
	}

	/**
	 * Returns the bank account information with the primary key.
	 *
	 * @param bankAccountInformationId the primary key of the bank account information
	 * @return the bank account information
	 * @throws PortalException if a bank account information with the primary key could not be found
	 */
	@Override
	public BankAccountInformation getBankAccountInformation(
			long bankAccountInformationId)
		throws PortalException {

		return bankAccountInformationPersistence.findByPrimaryKey(
			bankAccountInformationId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			bankAccountInformationLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(BankAccountInformation.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"bankAccountInformationId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			bankAccountInformationLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			BankAccountInformation.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"bankAccountInformationId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			bankAccountInformationLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(BankAccountInformation.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"bankAccountInformationId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return bankAccountInformationPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return bankAccountInformationLocalService.deleteBankAccountInformation(
			(BankAccountInformation)persistedModel);
	}

	@Override
	public BasePersistence<BankAccountInformation> getBasePersistence() {
		return bankAccountInformationPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return bankAccountInformationPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns a range of all the bank account informations.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>bd.gov.dgfood.common.services.model.impl.BankAccountInformationModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of bank account informations
	 * @param end the upper bound of the range of bank account informations (not inclusive)
	 * @return the range of bank account informations
	 */
	@Override
	public List<BankAccountInformation> getBankAccountInformations(
		int start, int end) {

		return bankAccountInformationPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of bank account informations.
	 *
	 * @return the number of bank account informations
	 */
	@Override
	public int getBankAccountInformationsCount() {
		return bankAccountInformationPersistence.countAll();
	}

	/**
	 * Updates the bank account information in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect BankAccountInformationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param bankAccountInformation the bank account information
	 * @return the bank account information that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public BankAccountInformation updateBankAccountInformation(
		BankAccountInformation bankAccountInformation) {

		return bankAccountInformationPersistence.update(bankAccountInformation);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			BankAccountInformationLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		bankAccountInformationLocalService =
			(BankAccountInformationLocalService)aopProxy;

		_setLocalServiceUtilService(bankAccountInformationLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return BankAccountInformationLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return BankAccountInformation.class;
	}

	protected String getModelClassName() {
		return BankAccountInformation.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				bankAccountInformationPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		BankAccountInformationLocalService bankAccountInformationLocalService) {

		try {
			Field field =
				BankAccountInformationLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, bankAccountInformationLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected AddressPersistence addressPersistence;

	@Reference
	protected AddressVersionPersistence addressVersionPersistence;

	@Reference
	protected APIAuditPersistence apiAuditPersistence;

	@Reference
	protected AttachmentPersistence attachmentPersistence;

	@Reference
	protected AttachmentVersionPersistence attachmentVersionPersistence;

	protected BankAccountInformationLocalService
		bankAccountInformationLocalService;

	@Reference
	protected BankAccountInformationPersistence
		bankAccountInformationPersistence;

	@Reference
	protected DeliveryOrderPersistence deliveryOrderPersistence;

	@Reference
	protected DGFUsersPersistence dgfUsersPersistence;

	@Reference
	protected GrievancePersistence grievancePersistence;

	@Reference
	protected IndentPersistence indentPersistence;

	@Reference
	protected MDMSyncStatusPersistence mdmSyncStatusPersistence;

	@Reference
	protected UserDetailsPersistence userDetailsPersistence;

	@Reference
	protected UserLocationPersistence userLocationPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}