/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.common.services.service.base;

import bd.gov.dgfood.common.services.model.Grievance;
import bd.gov.dgfood.common.services.service.GrievanceLocalService;
import bd.gov.dgfood.common.services.service.GrievanceLocalServiceUtil;
import bd.gov.dgfood.common.services.service.persistence.APIAuditPersistence;
import bd.gov.dgfood.common.services.service.persistence.AddressPersistence;
import bd.gov.dgfood.common.services.service.persistence.AddressVersionPersistence;
import bd.gov.dgfood.common.services.service.persistence.AttachmentPersistence;
import bd.gov.dgfood.common.services.service.persistence.AttachmentVersionPersistence;
import bd.gov.dgfood.common.services.service.persistence.BankAccountInformationPersistence;
import bd.gov.dgfood.common.services.service.persistence.DGFUsersPersistence;
import bd.gov.dgfood.common.services.service.persistence.DeliveryOrderPersistence;
import bd.gov.dgfood.common.services.service.persistence.GrievancePersistence;
import bd.gov.dgfood.common.services.service.persistence.IndentPersistence;
import bd.gov.dgfood.common.services.service.persistence.MDMSyncStatusPersistence;
import bd.gov.dgfood.common.services.service.persistence.UserDetailsPersistence;
import bd.gov.dgfood.common.services.service.persistence.UserLocationPersistence;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the grievance local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link bd.gov.dgfood.common.services.service.impl.GrievanceLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see bd.gov.dgfood.common.services.service.impl.GrievanceLocalServiceImpl
 * @generated
 */
public abstract class GrievanceLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, GrievanceLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>GrievanceLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>GrievanceLocalServiceUtil</code>.
	 */

	/**
	 * Adds the grievance to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect GrievanceLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param grievance the grievance
	 * @return the grievance that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Grievance addGrievance(Grievance grievance) {
		grievance.setNew(true);

		return grievancePersistence.update(grievance);
	}

	/**
	 * Creates a new grievance with the primary key. Does not add the grievance to the database.
	 *
	 * @param grievanceId the primary key for the new grievance
	 * @return the new grievance
	 */
	@Override
	@Transactional(enabled = false)
	public Grievance createGrievance(long grievanceId) {
		return grievancePersistence.create(grievanceId);
	}

	/**
	 * Deletes the grievance with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect GrievanceLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param grievanceId the primary key of the grievance
	 * @return the grievance that was removed
	 * @throws PortalException if a grievance with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Grievance deleteGrievance(long grievanceId) throws PortalException {
		return grievancePersistence.remove(grievanceId);
	}

	/**
	 * Deletes the grievance from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect GrievanceLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param grievance the grievance
	 * @return the grievance that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Grievance deleteGrievance(Grievance grievance) {
		return grievancePersistence.remove(grievance);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return grievancePersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			Grievance.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return grievancePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>bd.gov.dgfood.common.services.model.impl.GrievanceModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return grievancePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>bd.gov.dgfood.common.services.model.impl.GrievanceModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return grievancePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return grievancePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return grievancePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public Grievance fetchGrievance(long grievanceId) {
		return grievancePersistence.fetchByPrimaryKey(grievanceId);
	}

	/**
	 * Returns the grievance matching the UUID and group.
	 *
	 * @param uuid the grievance's UUID
	 * @param groupId the primary key of the group
	 * @return the matching grievance, or <code>null</code> if a matching grievance could not be found
	 */
	@Override
	public Grievance fetchGrievanceByUuidAndGroupId(String uuid, long groupId) {
		return grievancePersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the grievance with the primary key.
	 *
	 * @param grievanceId the primary key of the grievance
	 * @return the grievance
	 * @throws PortalException if a grievance with the primary key could not be found
	 */
	@Override
	public Grievance getGrievance(long grievanceId) throws PortalException {
		return grievancePersistence.findByPrimaryKey(grievanceId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(grievanceLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Grievance.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("grievanceId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			grievanceLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Grievance.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"grievanceId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(grievanceLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Grievance.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("grievanceId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return grievancePersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return grievanceLocalService.deleteGrievance((Grievance)persistedModel);
	}

	@Override
	public BasePersistence<Grievance> getBasePersistence() {
		return grievancePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return grievancePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the grievances matching the UUID and company.
	 *
	 * @param uuid the UUID of the grievances
	 * @param companyId the primary key of the company
	 * @return the matching grievances, or an empty list if no matches were found
	 */
	@Override
	public List<Grievance> getGrievancesByUuidAndCompanyId(
		String uuid, long companyId) {

		return grievancePersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of grievances matching the UUID and company.
	 *
	 * @param uuid the UUID of the grievances
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of grievances
	 * @param end the upper bound of the range of grievances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching grievances, or an empty list if no matches were found
	 */
	@Override
	public List<Grievance> getGrievancesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<Grievance> orderByComparator) {

		return grievancePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the grievance matching the UUID and group.
	 *
	 * @param uuid the grievance's UUID
	 * @param groupId the primary key of the group
	 * @return the matching grievance
	 * @throws PortalException if a matching grievance could not be found
	 */
	@Override
	public Grievance getGrievanceByUuidAndGroupId(String uuid, long groupId)
		throws PortalException {

		return grievancePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the grievances.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>bd.gov.dgfood.common.services.model.impl.GrievanceModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of grievances
	 * @param end the upper bound of the range of grievances (not inclusive)
	 * @return the range of grievances
	 */
	@Override
	public List<Grievance> getGrievances(int start, int end) {
		return grievancePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of grievances.
	 *
	 * @return the number of grievances
	 */
	@Override
	public int getGrievancesCount() {
		return grievancePersistence.countAll();
	}

	/**
	 * Updates the grievance in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect GrievanceLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param grievance the grievance
	 * @return the grievance that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Grievance updateGrievance(Grievance grievance) {
		return grievancePersistence.update(grievance);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			GrievanceLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		grievanceLocalService = (GrievanceLocalService)aopProxy;

		_setLocalServiceUtilService(grievanceLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return GrievanceLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Grievance.class;
	}

	protected String getModelClassName() {
		return Grievance.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = grievancePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		GrievanceLocalService grievanceLocalService) {

		try {
			Field field = GrievanceLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, grievanceLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected AddressPersistence addressPersistence;

	@Reference
	protected AddressVersionPersistence addressVersionPersistence;

	@Reference
	protected APIAuditPersistence apiAuditPersistence;

	@Reference
	protected AttachmentPersistence attachmentPersistence;

	@Reference
	protected AttachmentVersionPersistence attachmentVersionPersistence;

	@Reference
	protected BankAccountInformationPersistence
		bankAccountInformationPersistence;

	@Reference
	protected DeliveryOrderPersistence deliveryOrderPersistence;

	@Reference
	protected DGFUsersPersistence dgfUsersPersistence;

	protected GrievanceLocalService grievanceLocalService;

	@Reference
	protected GrievancePersistence grievancePersistence;

	@Reference
	protected IndentPersistence indentPersistence;

	@Reference
	protected MDMSyncStatusPersistence mdmSyncStatusPersistence;

	@Reference
	protected UserDetailsPersistence userDetailsPersistence;

	@Reference
	protected UserLocationPersistence userLocationPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}