/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.food.friendly.program.service.base;

import bd.gov.dgfood.food.friendly.program.model.FFPBeneficiaryVersion;
import bd.gov.dgfood.food.friendly.program.service.FFPBeneficiaryVersionService;
import bd.gov.dgfood.food.friendly.program.service.FFPBeneficiaryVersionServiceUtil;
import bd.gov.dgfood.food.friendly.program.service.persistence.FFPBeneficiaryPersistence;
import bd.gov.dgfood.food.friendly.program.service.persistence.FFPBeneficiaryVersionPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import java.lang.reflect.Field;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the ffp beneficiary version remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link bd.gov.dgfood.food.friendly.program.service.impl.FFPBeneficiaryVersionServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see bd.gov.dgfood.food.friendly.program.service.impl.FFPBeneficiaryVersionServiceImpl
 * @generated
 */
public abstract class FFPBeneficiaryVersionServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, FFPBeneficiaryVersionService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>FFPBeneficiaryVersionService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>FFPBeneficiaryVersionServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		_setServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			FFPBeneficiaryVersionService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		ffpBeneficiaryVersionService = (FFPBeneficiaryVersionService)aopProxy;

		_setServiceUtilService(ffpBeneficiaryVersionService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return FFPBeneficiaryVersionService.class.getName();
	}

	protected Class<?> getModelClass() {
		return FFPBeneficiaryVersion.class;
	}

	protected String getModelClassName() {
		return FFPBeneficiaryVersion.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				ffpBeneficiaryVersionPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		FFPBeneficiaryVersionService ffpBeneficiaryVersionService) {

		try {
			Field field =
				FFPBeneficiaryVersionServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, ffpBeneficiaryVersionService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected FFPBeneficiaryPersistence ffpBeneficiaryPersistence;

	@Reference
	protected bd.gov.dgfood.food.friendly.program.service.
		FFPBeneficiaryVersionLocalService ffpBeneficiaryVersionLocalService;

	protected FFPBeneficiaryVersionService ffpBeneficiaryVersionService;

	@Reference
	protected FFPBeneficiaryVersionPersistence ffpBeneficiaryVersionPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	@Reference
	protected com.liferay.portal.kernel.service.WorkflowInstanceLinkLocalService
		workflowInstanceLinkLocalService;

}