/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.common.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the BankAccountInformation service. Represents a row in the &quot;DGF_BankAccountInformation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>bd.gov.dgfood.common.services.model.impl.BankAccountInformationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>bd.gov.dgfood.common.services.model.impl.BankAccountInformationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BankAccountInformation
 * @generated
 */
@ProviderType
public interface BankAccountInformationModel
	extends AttachedModel, BaseModel<BankAccountInformation> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bank account information model instance should use the {@link BankAccountInformation} interface instead.
	 */

	/**
	 * Returns the primary key of this bank account information.
	 *
	 * @return the primary key of this bank account information
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bank account information.
	 *
	 * @param primaryKey the primary key of this bank account information
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this bank account information.
	 *
	 * @return the uuid of this bank account information
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this bank account information.
	 *
	 * @param uuid the uuid of this bank account information
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the bank account information ID of this bank account information.
	 *
	 * @return the bank account information ID of this bank account information
	 */
	public long getBankAccountInformationId();

	/**
	 * Sets the bank account information ID of this bank account information.
	 *
	 * @param bankAccountInformationId the bank account information ID of this bank account information
	 */
	public void setBankAccountInformationId(long bankAccountInformationId);

	/**
	 * Returns the created by of this bank account information.
	 *
	 * @return the created by of this bank account information
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this bank account information.
	 *
	 * @param createdBy the created by of this bank account information
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the create date of this bank account information.
	 *
	 * @return the create date of this bank account information
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this bank account information.
	 *
	 * @param createDate the create date of this bank account information
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the account number of this bank account information.
	 *
	 * @return the account number of this bank account information
	 */
	@AutoEscape
	public String getAccountNumber();

	/**
	 * Sets the account number of this bank account information.
	 *
	 * @param accountNumber the account number of this bank account information
	 */
	public void setAccountNumber(String accountNumber);

	/**
	 * Returns the bank name of this bank account information.
	 *
	 * @return the bank name of this bank account information
	 */
	@AutoEscape
	public String getBankName();

	/**
	 * Sets the bank name of this bank account information.
	 *
	 * @param bankName the bank name of this bank account information
	 */
	public void setBankName(String bankName);

	/**
	 * Returns the branch name of this bank account information.
	 *
	 * @return the branch name of this bank account information
	 */
	@AutoEscape
	public String getBranchName();

	/**
	 * Sets the branch name of this bank account information.
	 *
	 * @param branchName the branch name of this bank account information
	 */
	public void setBranchName(String branchName);

	/**
	 * Returns the routing code of this bank account information.
	 *
	 * @return the routing code of this bank account information
	 */
	@AutoEscape
	public String getRoutingCode();

	/**
	 * Sets the routing code of this bank account information.
	 *
	 * @param routingCode the routing code of this bank account information
	 */
	public void setRoutingCode(String routingCode);

	/**
	 * Returns the status of this bank account information.
	 *
	 * @return the status of this bank account information
	 */
	public int getStatus();

	/**
	 * Sets the status of this bank account information.
	 *
	 * @param status the status of this bank account information
	 */
	public void setStatus(int status);

	/**
	 * Returns the version of this bank account information.
	 *
	 * @return the version of this bank account information
	 */
	@AutoEscape
	public String getVersion();

	/**
	 * Sets the version of this bank account information.
	 *
	 * @param version the version of this bank account information
	 */
	public void setVersion(String version);

	/**
	 * Returns the class pk of this bank account information.
	 *
	 * @return the class pk of this bank account information
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this bank account information.
	 *
	 * @param classPK the class pk of this bank account information
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the fully qualified class name of this bank account information.
	 *
	 * @return the fully qualified class name of this bank account information
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this bank account information.
	 *
	 * @return the class name ID of this bank account information
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this bank account information.
	 *
	 * @param classNameId the class name ID of this bank account information
	 */
	@Override
	public void setClassNameId(long classNameId);

	@Override
	public BankAccountInformation cloneWithOriginalValues();

}