/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.common.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Indent service. Represents a row in the &quot;DGF_Indent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>bd.gov.dgfood.common.services.model.impl.IndentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>bd.gov.dgfood.common.services.model.impl.IndentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Indent
 * @generated
 */
@ProviderType
public interface IndentModel
	extends BaseModel<Indent>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a indent model instance should use the {@link Indent} interface instead.
	 */

	/**
	 * Returns the primary key of this indent.
	 *
	 * @return the primary key of this indent
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this indent.
	 *
	 * @param primaryKey the primary key of this indent
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this indent.
	 *
	 * @return the uuid of this indent
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this indent.
	 *
	 * @param uuid the uuid of this indent
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the indent ID of this indent.
	 *
	 * @return the indent ID of this indent
	 */
	public long getIndentId();

	/**
	 * Sets the indent ID of this indent.
	 *
	 * @param indentId the indent ID of this indent
	 */
	public void setIndentId(long indentId);

	/**
	 * Returns the allocation ID of this indent.
	 *
	 * @return the allocation ID of this indent
	 */
	public long getAllocationId();

	/**
	 * Sets the allocation ID of this indent.
	 *
	 * @param allocationId the allocation ID of this indent
	 */
	public void setAllocationId(long allocationId);

	/**
	 * Returns the commodity of this indent.
	 *
	 * @return the commodity of this indent
	 */
	@AutoEscape
	public String getCommodity();

	/**
	 * Sets the commodity of this indent.
	 *
	 * @param commodity the commodity of this indent
	 */
	public void setCommodity(String commodity);

	/**
	 * Returns the commodity description of this indent.
	 *
	 * @return the commodity description of this indent
	 */
	@AutoEscape
	public String getCommodityDescription();

	/**
	 * Sets the commodity description of this indent.
	 *
	 * @param commodityDescription the commodity description of this indent
	 */
	public void setCommodityDescription(String commodityDescription);

	/**
	 * Returns the quantity of this indent.
	 *
	 * @return the quantity of this indent
	 */
	public double getQuantity();

	/**
	 * Sets the quantity of this indent.
	 *
	 * @param quantity the quantity of this indent
	 */
	public void setQuantity(double quantity);

	/**
	 * Returns the quantity unit of this indent.
	 *
	 * @return the quantity unit of this indent
	 */
	@AutoEscape
	public String getQuantityUnit();

	/**
	 * Sets the quantity unit of this indent.
	 *
	 * @param quantityUnit the quantity unit of this indent
	 */
	public void setQuantityUnit(String quantityUnit);

	/**
	 * Returns the required delivery date of this indent.
	 *
	 * @return the required delivery date of this indent
	 */
	public Date getRequiredDeliveryDate();

	/**
	 * Sets the required delivery date of this indent.
	 *
	 * @param requiredDeliveryDate the required delivery date of this indent
	 */
	public void setRequiredDeliveryDate(Date requiredDeliveryDate);

	/**
	 * Returns the food grainissue date of this indent.
	 *
	 * @return the food grainissue date of this indent
	 */
	public Date getFoodGrainissueDate();

	/**
	 * Sets the food grainissue date of this indent.
	 *
	 * @param foodGrainissueDate the food grainissue date of this indent
	 */
	public void setFoodGrainissueDate(Date foodGrainissueDate);

	/**
	 * Returns the net price of this indent.
	 *
	 * @return the net price of this indent
	 */
	public double getNetPrice();

	/**
	 * Sets the net price of this indent.
	 *
	 * @param netPrice the net price of this indent
	 */
	public void setNetPrice(double netPrice);

	/**
	 * Returns the net price currency key of this indent.
	 *
	 * @return the net price currency key of this indent
	 */
	@AutoEscape
	public String getNetPriceCurrencyKey();

	/**
	 * Sets the net price currency key of this indent.
	 *
	 * @param netPriceCurrencyKey the net price currency key of this indent
	 */
	public void setNetPriceCurrencyKey(String netPriceCurrencyKey);

	/**
	 * Returns the net value of this indent.
	 *
	 * @return the net value of this indent
	 */
	public double getNetValue();

	/**
	 * Sets the net value of this indent.
	 *
	 * @param netValue the net value of this indent
	 */
	public void setNetValue(double netValue);

	/**
	 * Returns the net value currency key of this indent.
	 *
	 * @return the net value currency key of this indent
	 */
	@AutoEscape
	public String getNetValueCurrencyKey();

	/**
	 * Sets the net value currency key of this indent.
	 *
	 * @param netValueCurrencyKey the net value currency key of this indent
	 */
	public void setNetValueCurrencyKey(String netValueCurrencyKey);

	/**
	 * Returns the sales office of this indent.
	 *
	 * @return the sales office of this indent
	 */
	@AutoEscape
	public String getSalesOffice();

	/**
	 * Sets the sales office of this indent.
	 *
	 * @param salesOffice the sales office of this indent
	 */
	public void setSalesOffice(String salesOffice);

	/**
	 * Returns the depo of this indent.
	 *
	 * @return the depo of this indent
	 */
	@AutoEscape
	public String getDepo();

	/**
	 * Sets the depo of this indent.
	 *
	 * @param depo the depo of this indent
	 */
	public void setDepo(String depo);

	/**
	 * Returns the repayment terms of this indent.
	 *
	 * @return the repayment terms of this indent
	 */
	@AutoEscape
	public String getRepaymentTerms();

	/**
	 * Sets the repayment terms of this indent.
	 *
	 * @param repaymentTerms the repayment terms of this indent
	 */
	public void setRepaymentTerms(String repaymentTerms);

	/**
	 * Returns the delivery terms of this indent.
	 *
	 * @return the delivery terms of this indent
	 */
	@AutoEscape
	public String getDeliveryTerms();

	/**
	 * Sets the delivery terms of this indent.
	 *
	 * @param deliveryTerms the delivery terms of this indent
	 */
	public void setDeliveryTerms(String deliveryTerms);

	/**
	 * Returns the group ID of this indent.
	 *
	 * @return the group ID of this indent
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this indent.
	 *
	 * @param groupId the group ID of this indent
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this indent.
	 *
	 * @return the company ID of this indent
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this indent.
	 *
	 * @param companyId the company ID of this indent
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this indent.
	 *
	 * @return the user ID of this indent
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this indent.
	 *
	 * @param userId the user ID of this indent
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this indent.
	 *
	 * @return the user uuid of this indent
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this indent.
	 *
	 * @param userUuid the user uuid of this indent
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this indent.
	 *
	 * @return the create date of this indent
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this indent.
	 *
	 * @param createDate the create date of this indent
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this indent.
	 *
	 * @return the modified date of this indent
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this indent.
	 *
	 * @param modifiedDate the modified date of this indent
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this indent.
	 *
	 * @return the status of this indent
	 */
	public int getStatus();

	/**
	 * Sets the status of this indent.
	 *
	 * @param status the status of this indent
	 */
	public void setStatus(int status);

	/**
	 * Returns the reason of this indent.
	 *
	 * @return the reason of this indent
	 */
	public int getReason();

	/**
	 * Sets the reason of this indent.
	 *
	 * @param reason the reason of this indent
	 */
	public void setReason(int reason);

	@Override
	public Indent cloneWithOriginalValues();

}