/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.common.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserLocation service. Represents a row in the &quot;DGF_UserLocation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>bd.gov.dgfood.common.services.model.impl.UserLocationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>bd.gov.dgfood.common.services.model.impl.UserLocationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserLocation
 * @generated
 */
@ProviderType
public interface UserLocationModel
	extends BaseModel<UserLocation>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user location model instance should use the {@link UserLocation} interface instead.
	 */

	/**
	 * Returns the primary key of this user location.
	 *
	 * @return the primary key of this user location
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user location.
	 *
	 * @param primaryKey the primary key of this user location
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this user location.
	 *
	 * @return the uuid of this user location
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this user location.
	 *
	 * @param uuid the uuid of this user location
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the user location ID of this user location.
	 *
	 * @return the user location ID of this user location
	 */
	public long getUserLocationId();

	/**
	 * Sets the user location ID of this user location.
	 *
	 * @param userLocationId the user location ID of this user location
	 */
	public void setUserLocationId(long userLocationId);

	/**
	 * Returns the company ID of this user location.
	 *
	 * @return the company ID of this user location
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this user location.
	 *
	 * @param companyId the company ID of this user location
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this user location.
	 *
	 * @return the group ID of this user location
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this user location.
	 *
	 * @param groupId the group ID of this user location
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the location name of this user location.
	 *
	 * @return the location name of this user location
	 */
	@AutoEscape
	public String getLocationName();

	/**
	 * Sets the location name of this user location.
	 *
	 * @param locationName the location name of this user location
	 */
	public void setLocationName(String locationName);

	/**
	 * Returns the location code of this user location.
	 *
	 * @return the location code of this user location
	 */
	@AutoEscape
	public String getLocationCode();

	/**
	 * Sets the location code of this user location.
	 *
	 * @param locationCode the location code of this user location
	 */
	public void setLocationCode(String locationCode);

	/**
	 * Returns the location ID of this user location.
	 *
	 * @return the location ID of this user location
	 */
	public long getLocationId();

	/**
	 * Sets the location ID of this user location.
	 *
	 * @param locationId the location ID of this user location
	 */
	public void setLocationId(long locationId);

	/**
	 * Returns the location type of this user location.
	 *
	 * @return the location type of this user location
	 */
	@AutoEscape
	public String getLocationType();

	/**
	 * Sets the location type of this user location.
	 *
	 * @param locationType the location type of this user location
	 */
	public void setLocationType(String locationType);

	/**
	 * Returns the user name of this user location.
	 *
	 * @return the user name of this user location
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this user location.
	 *
	 * @param userName the user name of this user location
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the user ID of this user location.
	 *
	 * @return the user ID of this user location
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this user location.
	 *
	 * @param userId the user ID of this user location
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user location.
	 *
	 * @return the user uuid of this user location
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user location.
	 *
	 * @param userUuid the user uuid of this user location
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the role key of this user location.
	 *
	 * @return the role key of this user location
	 */
	@AutoEscape
	public String getRoleKey();

	/**
	 * Sets the role key of this user location.
	 *
	 * @param roleKey the role key of this user location
	 */
	public void setRoleKey(String roleKey);

	/**
	 * Returns the create date of this user location.
	 *
	 * @return the create date of this user location
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this user location.
	 *
	 * @param createDate the create date of this user location
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user location.
	 *
	 * @return the modified date of this user location
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user location.
	 *
	 * @param modifiedDate the modified date of this user location
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the created by of this user location.
	 *
	 * @return the created by of this user location
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this user location.
	 *
	 * @param createdBy the created by of this user location
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this user location.
	 *
	 * @return the modified by of this user location
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this user location.
	 *
	 * @param modifiedBy the modified by of this user location
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public UserLocation cloneWithOriginalValues();

}