/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.movement.contractor.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.io.Serializable;

import java.util.Date;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MovementContractor service. Represents a row in the &quot;DGFOOD_MovementContractor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>bd.gov.dgfood.movement.contractor.model.impl.MovementContractorModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>bd.gov.dgfood.movement.contractor.model.impl.MovementContractorImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MovementContractor
 * @generated
 */
@ProviderType
public interface MovementContractorModel
	extends BaseModel<MovementContractor>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a movement contractor model instance should use the {@link MovementContractor} interface instead.
	 */

	/**
	 * Returns the primary key of this movement contractor.
	 *
	 * @return the primary key of this movement contractor
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this movement contractor.
	 *
	 * @param primaryKey the primary key of this movement contractor
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this movement contractor.
	 *
	 * @return the uuid of this movement contractor
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this movement contractor.
	 *
	 * @param uuid the uuid of this movement contractor
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the movement contractor ID of this movement contractor.
	 *
	 * @return the movement contractor ID of this movement contractor
	 */
	public long getMovementContractorId();

	/**
	 * Sets the movement contractor ID of this movement contractor.
	 *
	 * @param movementContractorId the movement contractor ID of this movement contractor
	 */
	public void setMovementContractorId(long movementContractorId);

	/**
	 * Returns the group ID of this movement contractor.
	 *
	 * @return the group ID of this movement contractor
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this movement contractor.
	 *
	 * @param groupId the group ID of this movement contractor
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this movement contractor.
	 *
	 * @return the company ID of this movement contractor
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this movement contractor.
	 *
	 * @param companyId the company ID of this movement contractor
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the name of this movement contractor.
	 *
	 * @return the name of this movement contractor
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this movement contractor.
	 *
	 * @param name the name of this movement contractor
	 */
	public void setName(String name);

	/**
	 * Returns the mobile number of this movement contractor.
	 *
	 * @return the mobile number of this movement contractor
	 */
	@AutoEscape
	public String getMobileNumber();

	/**
	 * Sets the mobile number of this movement contractor.
	 *
	 * @param mobileNumber the mobile number of this movement contractor
	 */
	public void setMobileNumber(String mobileNumber);

	/**
	 * Returns the national ID of this movement contractor.
	 *
	 * @return the national ID of this movement contractor
	 */
	public long getNationalId();

	/**
	 * Sets the national ID of this movement contractor.
	 *
	 * @param nationalId the national ID of this movement contractor
	 */
	public void setNationalId(long nationalId);

	/**
	 * Returns the email address of this movement contractor.
	 *
	 * @return the email address of this movement contractor
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this movement contractor.
	 *
	 * @param emailAddress the email address of this movement contractor
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the date of birth of this movement contractor.
	 *
	 * @return the date of birth of this movement contractor
	 */
	public Date getDateOfBirth();

	/**
	 * Sets the date of birth of this movement contractor.
	 *
	 * @param dateOfBirth the date of birth of this movement contractor
	 */
	public void setDateOfBirth(Date dateOfBirth);

	/**
	 * Returns the gender of this movement contractor.
	 *
	 * @return the gender of this movement contractor
	 */
	public int getGender();

	/**
	 * Sets the gender of this movement contractor.
	 *
	 * @param gender the gender of this movement contractor
	 */
	public void setGender(int gender);

	/**
	 * Returns the father name of this movement contractor.
	 *
	 * @return the father name of this movement contractor
	 */
	@AutoEscape
	public String getFatherName();

	/**
	 * Sets the father name of this movement contractor.
	 *
	 * @param fatherName the father name of this movement contractor
	 */
	public void setFatherName(String fatherName);

	/**
	 * Returns the mother name of this movement contractor.
	 *
	 * @return the mother name of this movement contractor
	 */
	@AutoEscape
	public String getMotherName();

	/**
	 * Sets the mother name of this movement contractor.
	 *
	 * @param motherName the mother name of this movement contractor
	 */
	public void setMotherName(String motherName);

	/**
	 * Returns the marital status of this movement contractor.
	 *
	 * @return the marital status of this movement contractor
	 */
	public int getMaritalStatus();

	/**
	 * Sets the marital status of this movement contractor.
	 *
	 * @param maritalStatus the marital status of this movement contractor
	 */
	public void setMaritalStatus(int maritalStatus);

	/**
	 * Returns the type of this movement contractor.
	 *
	 * @return the type of this movement contractor
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this movement contractor.
	 *
	 * @param type the type of this movement contractor
	 */
	public void setType(String type);

	/**
	 * Returns the organization name of this movement contractor.
	 *
	 * @return the organization name of this movement contractor
	 */
	@AutoEscape
	public String getOrganizationName();

	/**
	 * Sets the organization name of this movement contractor.
	 *
	 * @param organizationName the organization name of this movement contractor
	 */
	public void setOrganizationName(String organizationName);

	/**
	 * Returns the trade license number of this movement contractor.
	 *
	 * @return the trade license number of this movement contractor
	 */
	@AutoEscape
	public String getTradeLicenseNumber();

	/**
	 * Sets the trade license number of this movement contractor.
	 *
	 * @param tradeLicenseNumber the trade license number of this movement contractor
	 */
	public void setTradeLicenseNumber(String tradeLicenseNumber);

	/**
	 * Returns the trade license expiry date of this movement contractor.
	 *
	 * @return the trade license expiry date of this movement contractor
	 */
	public Date getTradeLicenseExpiryDate();

	/**
	 * Sets the trade license expiry date of this movement contractor.
	 *
	 * @param tradeLicenseExpiryDate the trade license expiry date of this movement contractor
	 */
	public void setTradeLicenseExpiryDate(Date tradeLicenseExpiryDate);

	/**
	 * Returns the vehicle of this movement contractor.
	 *
	 * @return the vehicle of this movement contractor
	 */
	@AutoEscape
	public String getVehicle();

	/**
	 * Sets the vehicle of this movement contractor.
	 *
	 * @param vehicle the vehicle of this movement contractor
	 */
	public void setVehicle(String vehicle);

	/**
	 * Returns the vehicle count of this movement contractor.
	 *
	 * @return the vehicle count of this movement contractor
	 */
	public int getVehicleCount();

	/**
	 * Sets the vehicle count of this movement contractor.
	 *
	 * @param vehicleCount the vehicle count of this movement contractor
	 */
	public void setVehicleCount(int vehicleCount);

	/**
	 * Returns the vehicle capacity of this movement contractor.
	 *
	 * @return the vehicle capacity of this movement contractor
	 */
	public Map<String, Serializable> getVehicleCapacity();

	/**
	 * Sets the vehicle capacity of this movement contractor.
	 *
	 * @param vehicleCapacity the vehicle capacity of this movement contractor
	 */
	public void setVehicleCapacity(Map<String, Serializable> vehicleCapacity);

	/**
	 * Returns the user ID of this movement contractor.
	 *
	 * @return the user ID of this movement contractor
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this movement contractor.
	 *
	 * @param userId the user ID of this movement contractor
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this movement contractor.
	 *
	 * @return the user uuid of this movement contractor
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this movement contractor.
	 *
	 * @param userUuid the user uuid of this movement contractor
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the password of this movement contractor.
	 *
	 * @return the password of this movement contractor
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this movement contractor.
	 *
	 * @param password the password of this movement contractor
	 */
	public void setPassword(String password);

	/**
	 * Returns the application number of this movement contractor.
	 *
	 * @return the application number of this movement contractor
	 */
	public long getApplicationNumber();

	/**
	 * Sets the application number of this movement contractor.
	 *
	 * @param applicationNumber the application number of this movement contractor
	 */
	public void setApplicationNumber(long applicationNumber);

	/**
	 * Returns the business code of this movement contractor.
	 *
	 * @return the business code of this movement contractor
	 */
	public long getBusinessCode();

	/**
	 * Sets the business code of this movement contractor.
	 *
	 * @param businessCode the business code of this movement contractor
	 */
	public void setBusinessCode(long businessCode);

	/**
	 * Returns the version of this movement contractor.
	 *
	 * @return the version of this movement contractor
	 */
	public double getVersion();

	/**
	 * Sets the version of this movement contractor.
	 *
	 * @param version the version of this movement contractor
	 */
	public void setVersion(double version);

	/**
	 * Returns the status of this movement contractor.
	 *
	 * @return the status of this movement contractor
	 */
	public int getStatus();

	/**
	 * Sets the status of this movement contractor.
	 *
	 * @param status the status of this movement contractor
	 */
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this movement contractor.
	 *
	 * @return the status by user ID of this movement contractor
	 */
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this movement contractor.
	 *
	 * @param statusByUserId the status by user ID of this movement contractor
	 */
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this movement contractor.
	 *
	 * @return the status by user uuid of this movement contractor
	 */
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this movement contractor.
	 *
	 * @param statusByUserUuid the status by user uuid of this movement contractor
	 */
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status date of this movement contractor.
	 *
	 * @return the status date of this movement contractor
	 */
	public Date getStatusDate();

	/**
	 * Sets the status date of this movement contractor.
	 *
	 * @param statusDate the status date of this movement contractor
	 */
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the created by of this movement contractor.
	 *
	 * @return the created by of this movement contractor
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this movement contractor.
	 *
	 * @param createdBy the created by of this movement contractor
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the create date of this movement contractor.
	 *
	 * @return the create date of this movement contractor
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this movement contractor.
	 *
	 * @param createDate the create date of this movement contractor
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified by of this movement contractor.
	 *
	 * @return the modified by of this movement contractor
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this movement contractor.
	 *
	 * @param modifiedBy the modified by of this movement contractor
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the modified date of this movement contractor.
	 *
	 * @return the modified date of this movement contractor
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this movement contractor.
	 *
	 * @param modifiedDate the modified date of this movement contractor
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public MovementContractor cloneWithOriginalValues();

}