info:
    description: "DgfoodHeadlessCommonDelivery REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "DgfoodHeadlessCommonDelivery"
    version: v1.0
openapi: 3.0.1
components:
    schemas:
        CaptchaAnswer:
            description:
                This Component returns captcha answer for a session.
            properties:
                answer:
                    readOnly: true
                    type: string
            type: object
        OTPGeneration:
            description:
                This Component returns otp number for a mobile number.
            properties:
                statusCode:
                    readOnly: true
                    type: integer
                errorMsg:
                    readOnly: true
                    type: string
                lockOutTime:
                    readOnly: true
                    type: string
                isLockOut:
                    readOnly: true
                    type: boolean
                exceededResendMaxAttempt:
                    readOnly: true
                    type: boolean                
            type: object
        OTPVerification:
            description:
                This Component is for verification of OTP number.
            properties:
                statusCode:
                    readOnly: true
                    type: integer
                errorMsg:
                    readOnly: true
                    type: string
                exceededVerifyMaxAttempt:
                    readOnly: true
                    type: boolean  
                isOtpExpired:
                    readOnly: true
                    type: boolean   
            type: object
        UserNotification:
            description: This Component returns Portal User Notifications.
            properties:
                id:
                    format: int64
                    type: integer
                title:
                    readOnly: true
                    type: string
                description:
                    readOnly: true
                    type: string
                time:
                    readOnly: true
                    type: string
                isRead:
                    readOnly: true
                    type: boolean
                unReadCount:
                    readOnly: true
                    type: integer
                
            type: object
        ChangePassword:
            description: For change password of existing user
            properties:
              nid:
                type: string
              oldPassword:
                type: string
              newPassword:
                type: string
              confirmPassword:
                type: string
              lang:
                type: string  
            type: object
        ForgetPassword:
          description: For Forget password of existing user
          properties:
            nid:
              type: string
            dateOfBirth:
              format: date
              type: string
            mobileNumber:
              format: int64
              type: integer
            lang:
              type: string  
          type: object
        UserResponse:
          description: For Response class for API
          properties:
            apiStatus:
             format: int32
             type: integer
            statusCode:
              format: int32
              type: integer
            message:
              description: Response status message of login, Forget, Change password.
              type: string
          type: object
paths:
    "/captcha/get-answer":
        get:
            description:
                This end point returns captcha answer for a session.
            operationId: getCaptchaAnswer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/CaptchaAnswer"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/CaptchaAnswer"
                    description:
                        ""
            tags: ["CaptchaAnswer"]
    "/otp/get-otp/{mobileno}":
        get:
            description:
                This Component returns otp number for a mobile number.
            operationId: getOTPNumber
            parameters:
                - in: path
                  name: mobileno
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/OTPGeneration"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/OTPGeneration"
                    description:
                        ""
            tags: ["OTPGeneration"]
    "/otp/resend-otp/{mobileno}":
        get:
            description:
                This Component returns otp number for a mobile number.
            operationId: resendOTPNumber
            parameters:
                - in: path
                  name: mobileno
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/OTPGeneration"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/OTPGeneration"
                    description:
                        ""
            tags: ["OTPGeneration"]
    "/otp/verify-otp/{mobileno}/{otpval}":
        get:
            description:
                This Component returns success or failure messages for opt verification.
            operationId: verifyOTP
            parameters:
                - in: path
                  name: mobileno
                  required: true
                  schema:
                      type: string
                - in: path
                  name: otpval
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/OTPVerification"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/OTPVerification"
                    description:
                        ""
            tags: ["OTPVerification"]
    "/user-notifications/{userNotificationUserId}":
        get:
            description:
                This end point returns notifications of a user.
            operationId: getUserNotificationsPage
            parameters:
                - in: path
                  name: userNotificationUserId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                   $ref: "#/components/schemas/UserNotification"
                                type: array
                        application/xml:
                            schema:
                                items:
                                   $ref: "#/components/schemas/UserNotification"
                                type: array
            tags: ["UserNotification"]
    "/user-notifications/{userNotificationUserId}/mark-as-read":
        post:
            description: Marks User Un Read Notification as Read.
            operationId: postUserNotificationsMarkAsRead
            parameters:
                - in: path
                  name: userNotificationUserId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            items:
                               $ref: "#/components/schemas/UserNotification"
                            type: array
                    application/xml:
                        schema:
                            items:
                               $ref: "#/components/schemas/UserNotification"
                            type: array
            responses:
                201:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["UserNotification"]
    "/user-notifications/{userNotificationUserId}/un-read-count":
        get:
            description:
                This end point returns Un Read notifications count of a user.
            operationId: getUserNotificationsUnReadCount
            parameters:
                - in: path
                  name: userNotificationUserId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/UserNotification"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/UserNotification"
            tags: ["UserNotification"]          
      
    "/login":
           get:
            description: User login url.
            operationId: getLogin
            parameters:
              - in: query
                name: nid
                schema:
                  type: string
              - in: query
                name: password
                schema:
                  type: string
              - in: query
                name: lang
                schema:
                  type: string   
            responses:
              '200':
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/UserResponse'
                  application/xml:
                    schema:
                      $ref: '#/components/schemas/UserResponse'
                description: ''
            tags: ["UserResponse"]
    "/change-password":
     post:
      description: Change a new password
      operationId: postChangePassword
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePassword'
          application/xml:
            schema:
              $ref: '#/components/schemas/ChangePassword'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/UserResponse'
          description: ''
      tags: ["UserResponse"]      
    "/forget-password":
     post:
      description: Change a new password
      operationId: postForgetPassword
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgetPassword'
          application/xml:
            schema:
              $ref: '#/components/schemas/ForgetPassword'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/UserResponse'
          description: ''
      tags: ["UserResponse"]
