/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.credit.other.priority.customer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SalesCustomerAllocation service. Represents a row in the &quot;DGFOOD_SalesCustomerAllocation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>bd.gov.dgfood.credit.other.priority.customer.model.impl.SalesCustomerAllocationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>bd.gov.dgfood.credit.other.priority.customer.model.impl.SalesCustomerAllocationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SalesCustomerAllocation
 * @generated
 */
@ProviderType
public interface SalesCustomerAllocationModel
	extends BaseModel<SalesCustomerAllocation>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sales customer allocation model instance should use the {@link SalesCustomerAllocation} interface instead.
	 */

	/**
	 * Returns the primary key of this sales customer allocation.
	 *
	 * @return the primary key of this sales customer allocation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sales customer allocation.
	 *
	 * @param primaryKey the primary key of this sales customer allocation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this sales customer allocation.
	 *
	 * @return the uuid of this sales customer allocation
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this sales customer allocation.
	 *
	 * @param uuid the uuid of this sales customer allocation
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the sales customer allocation ID of this sales customer allocation.
	 *
	 * @return the sales customer allocation ID of this sales customer allocation
	 */
	public long getSalesCustomerAllocationId();

	/**
	 * Sets the sales customer allocation ID of this sales customer allocation.
	 *
	 * @param salesCustomerAllocationId the sales customer allocation ID of this sales customer allocation
	 */
	public void setSalesCustomerAllocationId(long salesCustomerAllocationId);

	/**
	 * Returns the sales customer code of this sales customer allocation.
	 *
	 * @return the sales customer code of this sales customer allocation
	 */
	public long getSalesCustomerCode();

	/**
	 * Sets the sales customer code of this sales customer allocation.
	 *
	 * @param salesCustomerCode the sales customer code of this sales customer allocation
	 */
	public void setSalesCustomerCode(long salesCustomerCode);

	/**
	 * Returns the sales customer name of this sales customer allocation.
	 *
	 * @return the sales customer name of this sales customer allocation
	 */
	@AutoEscape
	public String getSalesCustomerName();

	/**
	 * Sets the sales customer name of this sales customer allocation.
	 *
	 * @param salesCustomerName the sales customer name of this sales customer allocation
	 */
	public void setSalesCustomerName(String salesCustomerName);

	/**
	 * Returns the allocation number of this sales customer allocation.
	 *
	 * @return the allocation number of this sales customer allocation
	 */
	public long getAllocationNumber();

	/**
	 * Sets the allocation number of this sales customer allocation.
	 *
	 * @param allocationNumber the allocation number of this sales customer allocation
	 */
	public void setAllocationNumber(long allocationNumber);

	/**
	 * Returns the sales organization of this sales customer allocation.
	 *
	 * @return the sales organization of this sales customer allocation
	 */
	@AutoEscape
	public String getSalesOrganization();

	/**
	 * Sets the sales organization of this sales customer allocation.
	 *
	 * @param salesOrganization the sales organization of this sales customer allocation
	 */
	public void setSalesOrganization(String salesOrganization);

	/**
	 * Returns the distribution channel of this sales customer allocation.
	 *
	 * @return the distribution channel of this sales customer allocation
	 */
	@AutoEscape
	public String getDistributionChannel();

	/**
	 * Sets the distribution channel of this sales customer allocation.
	 *
	 * @param distributionChannel the distribution channel of this sales customer allocation
	 */
	public void setDistributionChannel(String distributionChannel);

	/**
	 * Returns the year of this sales customer allocation.
	 *
	 * @return the year of this sales customer allocation
	 */
	public int getYear();

	/**
	 * Sets the year of this sales customer allocation.
	 *
	 * @param year the year of this sales customer allocation
	 */
	public void setYear(int year);

	/**
	 * Returns the district of this sales customer allocation.
	 *
	 * @return the district of this sales customer allocation
	 */
	@AutoEscape
	public String getDistrict();

	/**
	 * Sets the district of this sales customer allocation.
	 *
	 * @param district the district of this sales customer allocation
	 */
	public void setDistrict(String district);

	/**
	 * Returns the sub district of this sales customer allocation.
	 *
	 * @return the sub district of this sales customer allocation
	 */
	@AutoEscape
	public String getSubDistrict();

	/**
	 * Sets the sub district of this sales customer allocation.
	 *
	 * @param subDistrict the sub district of this sales customer allocation
	 */
	public void setSubDistrict(String subDistrict);

	/**
	 * Returns the gov order number of this sales customer allocation.
	 *
	 * @return the gov order number of this sales customer allocation
	 */
	@AutoEscape
	public String getGovOrderNumber();

	/**
	 * Sets the gov order number of this sales customer allocation.
	 *
	 * @param govOrderNumber the gov order number of this sales customer allocation
	 */
	public void setGovOrderNumber(String govOrderNumber);

	/**
	 * Returns the commodity of this sales customer allocation.
	 *
	 * @return the commodity of this sales customer allocation
	 */
	@AutoEscape
	public String getCommodity();

	/**
	 * Sets the commodity of this sales customer allocation.
	 *
	 * @param commodity the commodity of this sales customer allocation
	 */
	public void setCommodity(String commodity);

	/**
	 * Returns the yearly qty of this sales customer allocation.
	 *
	 * @return the yearly qty of this sales customer allocation
	 */
	public double getYearlyQty();

	/**
	 * Sets the yearly qty of this sales customer allocation.
	 *
	 * @param yearlyQty the yearly qty of this sales customer allocation
	 */
	public void setYearlyQty(double yearlyQty);

	/**
	 * Returns the yearly qty unit of this sales customer allocation.
	 *
	 * @return the yearly qty unit of this sales customer allocation
	 */
	@AutoEscape
	public String getYearlyQtyUnit();

	/**
	 * Sets the yearly qty unit of this sales customer allocation.
	 *
	 * @param yearlyQtyUnit the yearly qty unit of this sales customer allocation
	 */
	public void setYearlyQtyUnit(String yearlyQtyUnit);

	/**
	 * Returns the monthly qty of this sales customer allocation.
	 *
	 * @return the monthly qty of this sales customer allocation
	 */
	public double getMonthlyQty();

	/**
	 * Sets the monthly qty of this sales customer allocation.
	 *
	 * @param monthlyQty the monthly qty of this sales customer allocation
	 */
	public void setMonthlyQty(double monthlyQty);

	/**
	 * Returns the monthly qty unit of this sales customer allocation.
	 *
	 * @return the monthly qty unit of this sales customer allocation
	 */
	@AutoEscape
	public String getMonthlyQtyUnit();

	/**
	 * Sets the monthly qty unit of this sales customer allocation.
	 *
	 * @param monthlyQtyUnit the monthly qty unit of this sales customer allocation
	 */
	public void setMonthlyQtyUnit(String monthlyQtyUnit);

	/**
	 * Returns the company ID of this sales customer allocation.
	 *
	 * @return the company ID of this sales customer allocation
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this sales customer allocation.
	 *
	 * @param companyId the company ID of this sales customer allocation
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this sales customer allocation.
	 *
	 * @return the create date of this sales customer allocation
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this sales customer allocation.
	 *
	 * @param createDate the create date of this sales customer allocation
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this sales customer allocation.
	 *
	 * @return the modified date of this sales customer allocation
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this sales customer allocation.
	 *
	 * @param modifiedDate the modified date of this sales customer allocation
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public SalesCustomerAllocation cloneWithOriginalValues();

}