/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.farmer.information.management.system.service.base;

import bd.gov.dgfood.farmer.information.management.system.model.FarmerRegistrationVersion;
import bd.gov.dgfood.farmer.information.management.system.service.FarmerRegistrationVersionLocalService;
import bd.gov.dgfood.farmer.information.management.system.service.FarmerRegistrationVersionLocalServiceUtil;
import bd.gov.dgfood.farmer.information.management.system.service.persistence.FarmerRegistrationPersistence;
import bd.gov.dgfood.farmer.information.management.system.service.persistence.FarmerRegistrationVersionPersistence;
import bd.gov.dgfood.farmer.information.management.system.service.persistence.FarmerSalesProposalPersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandler;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerRegistryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Criterion;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Disjunction;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.dao.orm.Property;
import com.liferay.portal.kernel.dao.orm.PropertyFactoryUtil;
import com.liferay.portal.kernel.dao.orm.RestrictionsFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the farmer registration version local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link bd.gov.dgfood.farmer.information.management.system.service.impl.FarmerRegistrationVersionLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see bd.gov.dgfood.farmer.information.management.system.service.impl.FarmerRegistrationVersionLocalServiceImpl
 * @generated
 */
public abstract class FarmerRegistrationVersionLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, FarmerRegistrationVersionLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>FarmerRegistrationVersionLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>FarmerRegistrationVersionLocalServiceUtil</code>.
	 */

	/**
	 * Adds the farmer registration version to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FarmerRegistrationVersionLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param farmerRegistrationVersion the farmer registration version
	 * @return the farmer registration version that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FarmerRegistrationVersion addFarmerRegistrationVersion(
		FarmerRegistrationVersion farmerRegistrationVersion) {

		farmerRegistrationVersion.setNew(true);

		return farmerRegistrationVersionPersistence.update(
			farmerRegistrationVersion);
	}

	/**
	 * Creates a new farmer registration version with the primary key. Does not add the farmer registration version to the database.
	 *
	 * @param farmerRegistrationVersionId the primary key for the new farmer registration version
	 * @return the new farmer registration version
	 */
	@Override
	@Transactional(enabled = false)
	public FarmerRegistrationVersion createFarmerRegistrationVersion(
		long farmerRegistrationVersionId) {

		return farmerRegistrationVersionPersistence.create(
			farmerRegistrationVersionId);
	}

	/**
	 * Deletes the farmer registration version with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FarmerRegistrationVersionLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param farmerRegistrationVersionId the primary key of the farmer registration version
	 * @return the farmer registration version that was removed
	 * @throws PortalException if a farmer registration version with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FarmerRegistrationVersion deleteFarmerRegistrationVersion(
			long farmerRegistrationVersionId)
		throws PortalException {

		return farmerRegistrationVersionPersistence.remove(
			farmerRegistrationVersionId);
	}

	/**
	 * Deletes the farmer registration version from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FarmerRegistrationVersionLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param farmerRegistrationVersion the farmer registration version
	 * @return the farmer registration version that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FarmerRegistrationVersion deleteFarmerRegistrationVersion(
		FarmerRegistrationVersion farmerRegistrationVersion) {

		return farmerRegistrationVersionPersistence.remove(
			farmerRegistrationVersion);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return farmerRegistrationVersionPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			FarmerRegistrationVersion.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return farmerRegistrationVersionPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>bd.gov.dgfood.farmer.information.management.system.model.impl.FarmerRegistrationVersionModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return farmerRegistrationVersionPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>bd.gov.dgfood.farmer.information.management.system.model.impl.FarmerRegistrationVersionModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return farmerRegistrationVersionPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return farmerRegistrationVersionPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return farmerRegistrationVersionPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public FarmerRegistrationVersion fetchFarmerRegistrationVersion(
		long farmerRegistrationVersionId) {

		return farmerRegistrationVersionPersistence.fetchByPrimaryKey(
			farmerRegistrationVersionId);
	}

	/**
	 * Returns the farmer registration version matching the UUID and group.
	 *
	 * @param uuid the farmer registration version's UUID
	 * @param groupId the primary key of the group
	 * @return the matching farmer registration version, or <code>null</code> if a matching farmer registration version could not be found
	 */
	@Override
	public FarmerRegistrationVersion
		fetchFarmerRegistrationVersionByUuidAndGroupId(
			String uuid, long groupId) {

		return farmerRegistrationVersionPersistence.fetchByUUID_G(
			uuid, groupId);
	}

	/**
	 * Returns the farmer registration version with the primary key.
	 *
	 * @param farmerRegistrationVersionId the primary key of the farmer registration version
	 * @return the farmer registration version
	 * @throws PortalException if a farmer registration version with the primary key could not be found
	 */
	@Override
	public FarmerRegistrationVersion getFarmerRegistrationVersion(
			long farmerRegistrationVersionId)
		throws PortalException {

		return farmerRegistrationVersionPersistence.findByPrimaryKey(
			farmerRegistrationVersionId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			farmerRegistrationVersionLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(FarmerRegistrationVersion.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"farmerRegistrationVersionId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			farmerRegistrationVersionLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			FarmerRegistrationVersion.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"farmerRegistrationVersionId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			farmerRegistrationVersionLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(FarmerRegistrationVersion.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"farmerRegistrationVersionId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					Criterion modifiedDateCriterion =
						portletDataContext.getDateRangeCriteria("modifiedDate");

					Criterion statusDateCriterion =
						portletDataContext.getDateRangeCriteria("statusDate");

					if ((modifiedDateCriterion != null) &&
						(statusDateCriterion != null)) {

						Disjunction disjunction =
							RestrictionsFactoryUtil.disjunction();

						disjunction.add(modifiedDateCriterion);
						disjunction.add(statusDateCriterion);

						dynamicQuery.add(disjunction);
					}

					Property workflowStatusProperty =
						PropertyFactoryUtil.forName("status");

					if (portletDataContext.isInitialPublication()) {
						dynamicQuery.add(
							workflowStatusProperty.ne(
								WorkflowConstants.STATUS_IN_TRASH));
					}
					else {
						StagedModelDataHandler<?> stagedModelDataHandler =
							StagedModelDataHandlerRegistryUtil.
								getStagedModelDataHandler(
									FarmerRegistrationVersion.class.getName());

						dynamicQuery.add(
							workflowStatusProperty.in(
								stagedModelDataHandler.
									getExportableStatuses()));
					}
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<FarmerRegistrationVersion>() {

				@Override
				public void performAction(
						FarmerRegistrationVersion farmerRegistrationVersion)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, farmerRegistrationVersion);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					FarmerRegistrationVersion.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return farmerRegistrationVersionPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return farmerRegistrationVersionLocalService.
			deleteFarmerRegistrationVersion(
				(FarmerRegistrationVersion)persistedModel);
	}

	@Override
	public BasePersistence<FarmerRegistrationVersion> getBasePersistence() {
		return farmerRegistrationVersionPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return farmerRegistrationVersionPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns all the farmer registration versions matching the UUID and company.
	 *
	 * @param uuid the UUID of the farmer registration versions
	 * @param companyId the primary key of the company
	 * @return the matching farmer registration versions, or an empty list if no matches were found
	 */
	@Override
	public List<FarmerRegistrationVersion>
		getFarmerRegistrationVersionsByUuidAndCompanyId(
			String uuid, long companyId) {

		return farmerRegistrationVersionPersistence.findByUuid_C(
			uuid, companyId);
	}

	/**
	 * Returns a range of farmer registration versions matching the UUID and company.
	 *
	 * @param uuid the UUID of the farmer registration versions
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of farmer registration versions
	 * @param end the upper bound of the range of farmer registration versions (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching farmer registration versions, or an empty list if no matches were found
	 */
	@Override
	public List<FarmerRegistrationVersion>
		getFarmerRegistrationVersionsByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<FarmerRegistrationVersion> orderByComparator) {

		return farmerRegistrationVersionPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the farmer registration version matching the UUID and group.
	 *
	 * @param uuid the farmer registration version's UUID
	 * @param groupId the primary key of the group
	 * @return the matching farmer registration version
	 * @throws PortalException if a matching farmer registration version could not be found
	 */
	@Override
	public FarmerRegistrationVersion
			getFarmerRegistrationVersionByUuidAndGroupId(
				String uuid, long groupId)
		throws PortalException {

		return farmerRegistrationVersionPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the farmer registration versions.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>bd.gov.dgfood.farmer.information.management.system.model.impl.FarmerRegistrationVersionModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of farmer registration versions
	 * @param end the upper bound of the range of farmer registration versions (not inclusive)
	 * @return the range of farmer registration versions
	 */
	@Override
	public List<FarmerRegistrationVersion> getFarmerRegistrationVersions(
		int start, int end) {

		return farmerRegistrationVersionPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of farmer registration versions.
	 *
	 * @return the number of farmer registration versions
	 */
	@Override
	public int getFarmerRegistrationVersionsCount() {
		return farmerRegistrationVersionPersistence.countAll();
	}

	/**
	 * Updates the farmer registration version in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FarmerRegistrationVersionLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param farmerRegistrationVersion the farmer registration version
	 * @return the farmer registration version that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FarmerRegistrationVersion updateFarmerRegistrationVersion(
		FarmerRegistrationVersion farmerRegistrationVersion) {

		return farmerRegistrationVersionPersistence.update(
			farmerRegistrationVersion);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			FarmerRegistrationVersionLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		farmerRegistrationVersionLocalService =
			(FarmerRegistrationVersionLocalService)aopProxy;

		_setLocalServiceUtilService(farmerRegistrationVersionLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return FarmerRegistrationVersionLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return FarmerRegistrationVersion.class;
	}

	protected String getModelClassName() {
		return FarmerRegistrationVersion.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				farmerRegistrationVersionPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		FarmerRegistrationVersionLocalService
			farmerRegistrationVersionLocalService) {

		try {
			Field field =
				FarmerRegistrationVersionLocalServiceUtil.class.
					getDeclaredField("_service");

			field.setAccessible(true);

			field.set(null, farmerRegistrationVersionLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected FarmerRegistrationPersistence farmerRegistrationPersistence;

	protected FarmerRegistrationVersionLocalService
		farmerRegistrationVersionLocalService;

	@Reference
	protected FarmerRegistrationVersionPersistence
		farmerRegistrationVersionPersistence;

	@Reference
	protected FarmerSalesProposalPersistence farmerSalesProposalPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryLocalService
		assetEntryLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetLinkLocalService
		assetLinkLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetTagLocalService
		assetTagLocalService;

}