
info:
    description: "DgfoodHeadlessFoodFriendlyProgram REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "DgfoodHeadlessFoodFriendlyProgram"
    version: v1.0
openapi: 3.0.1
components:
    schemas:
        FFPBeneficiaryAccount:
            description: Contains all of the data for a single FFPBeneficiary.
            properties:
                id:
                    description: The beneficiary internal ID..
                    format: int64
                    readOnly: true
                    type: integer
                cardNumber:
                    readOnly: true
                    type: string
                nationalId:
                    format: int64
                    type: integer
                name:
                    type: string
                birthDate:
                    description: The beneficiary's date of birth, in ISO 8601 format.
                    format: date-time
                    type: string
                mobileNumber:
                    type: string
                emailAddress:
                    type: string
                gender:
                    type: integer
                fatherName:
                    type: string
                motherName:
                    type: string
                maritalStatus:
                    type: integer
                spouseName:
                    type: string
                spouseFatherName:
                    type: string
                spouseBirthDate:
                    description: The beneficiary's spouse date of birth, in ISO 8601 format.
                    format: date-time
                    type: string
                spouseNationalId:
                    format: int64
                    type: integer
                familyAverageMonthlyIncome:
                    type: string
                familyEarningMembers:
                    type: integer
                status:
                    description: The beneficiary's status (approved, pending, rejected).
                    type: integer
                version:
                    description: The latest version of the approved benficiary's details.
                    format: double
                    type: number
                createdBy:
                    description: The Union Chairman Id.
                    format: int64
                    type: integer
                modifiedBy:
                    description: The Union Chairman Id.
                    format: int64
                    type: integer
                dateCreated:
                    format: date-time
                    readOnly: true
                    type: string
                dateModified:
                    format: date-time
                    readOnly: true
                    type: string
                presentAddress:
                    $ref: "#/components/schemas/Address"
                permanentAddress:
                    $ref: "#/components/schemas/Address"
                photograph:
                    type: string
                signature:
                    type: string
                acknowledge:
                    type: boolean
                nonOfMyFamilyMembersRegisteredEarlier:
                    type: boolean
                additionalDocuments:
                    items:
                        type: string
                    type: array
                sameAsPermanentAddress:
                    type: boolean
                dealer:
                    items:
                        $ref: "#/components/schemas/Dealer"
                    type: object
            type: object
        Address:
            description: Represents the beneficiary's contact information.
            properties:
                region:
                    properties:
                        id:
                            format: int64
                            type: integer
                        value:
                            readOnly: true
                            type: string

                    type: object
                district:
                    properties:
                        id:
                            format: int64
                            type: integer
                        value:
                            readOnly: true
                            type: string
                    type: object
                upzilla:
                    properties:
                        id:
                            format: int64
                            type: integer
                        value:
                            readOnly: true
                            type: string
                    type: object
                union:
                    properties:
                        id:
                            format: int64
                            type: integer
                        value:
                            readOnly: true
                            type: string
                    type: object
                ward:
                    properties:
                        id:
                            format: int64
                            type: integer
                        value:
                            readOnly: true
                            type: string
                    type: object
                postOffice:
                    type: string
                zipCode:
                    format: int64
                    type: integer
                village:
                    type: string
                address:
                    type: string
            type: object
        Dealer:
            description: Represents the dealer information to whom beneficiary will be linked.
            properties:
                dealerName:
                    type: string
                    readOnly: true
                dealerCode:
                    type: string
                    readOnly: true
                shopName:
                    type: string
                    readOnly: true
                shopAddress:
                    type: string
                    readOnly: true
            type: object
paths:
    "/ffp-beneficiary-accounts":
        get:
            description: Retrieves the ffp beneficiaries. Results can be paginated, filtered, and searched.
            operationId: getFFPBeneficiaryAccountsPage
            parameters:
                - in: query
                  name: keywords
                  schema:
                      type: string
                - in: query
                  name: filter
                  schema:
                      type: string
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: sort
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/FFPBeneficiaryAccount"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/FFPBeneficiaryAccount"
                                type: array
                    description: ""
            tags: ["FFPBeneficiaryAccount"]
        post:
            description: Creates a new ffp beneficiary
            operationId: postFFPBeneficiaryAccount
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/FFPBeneficiaryAccount"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/FFPBeneficiaryAccount"
            responses:
                201:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/FFPBeneficiaryAccount"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/FFPBeneficiaryAccount"
                    description: ""
            tags: ["FFPBeneficiaryAccount"]
    "/ffp-beneficiary-accounts/{ffpBeneficiaryAccountId}":
        get:
            description: Retrieves the beneficiary details.
            operationId: getFFPBeneficiaryAccount
            parameters:
                - in: path
                  name: ffpBeneficiaryAccountId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/FFPBeneficiaryAccount"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/FFPBeneficiaryAccount"
                    description: ""
            tags: ["FFPBeneficiaryAccount"]
        put:
            description:
                Update the beneficiary details with information sent in the request body as a new version. Any missing fields are deleted
                unless they are required.
            operationId: putFFPBeneficiaryAccount
            parameters:
                - in: path
                  name: ffpBeneficiaryAccountId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/FFPBeneficiaryAccount"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/FFPBeneficiaryAccount"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/FFPBeneficiaryAccount"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/FFPBeneficiaryAccount"
                    description: "FFPBeneficiary details successfully updated"
            tags: ["FFPBeneficiaryAccount"]
