/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.food.friendly.program.model.impl;

import bd.gov.dgfood.food.friendly.program.model.FFPBeneficiaryVersion;
import bd.gov.dgfood.food.friendly.program.model.FFPBeneficiaryVersionModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FFPBeneficiaryVersion service. Represents a row in the &quot;FFPB_RegistrationVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FFPBeneficiaryVersionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FFPBeneficiaryVersionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FFPBeneficiaryVersionImpl
 * @generated
 */
@JSON(strict = true)
public class FFPBeneficiaryVersionModelImpl
	extends BaseModelImpl<FFPBeneficiaryVersion>
	implements FFPBeneficiaryVersionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ffp beneficiary version model instance should use the <code>FFPBeneficiaryVersion</code> interface instead.
	 */
	public static final String TABLE_NAME = "FFPB_RegistrationVersion";

	public static final Object[][] TABLE_COLUMNS = {
		{"beneficiaryVersionId", Types.BIGINT}, {"beneficiaryId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"version", Types.DOUBLE}, {"name", Types.VARCHAR},
		{"mobileNumber", Types.VARCHAR}, {"nationalId", Types.BIGINT},
		{"emailAddress", Types.VARCHAR}, {"cardNumber", Types.VARCHAR},
		{"dateOfBirth", Types.TIMESTAMP}, {"gender", Types.INTEGER},
		{"fatherName", Types.VARCHAR}, {"motherName", Types.VARCHAR},
		{"maritalStatus", Types.INTEGER}, {"spouseName", Types.VARCHAR},
		{"spouseFatherName", Types.VARCHAR},
		{"spouseDateOfBirth", Types.TIMESTAMP},
		{"spouseNationalId", Types.BIGINT},
		{"familyAverageMonthlyIncome", Types.VARCHAR},
		{"familyEarningMembers", Types.INTEGER}, {"acknowledge", Types.BOOLEAN},
		{"nonOfMyFamilyMembersRegistered", Types.BOOLEAN},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusDate", Types.TIMESTAMP}, {"createdBy", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("beneficiaryVersionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("beneficiaryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("version", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mobileNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nationalId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("emailAddress", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("cardNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dateOfBirth", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("gender", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("fatherName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("motherName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("maritalStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("spouseName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("spouseFatherName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("spouseDateOfBirth", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("spouseNationalId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("familyAverageMonthlyIncome", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("familyEarningMembers", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("acknowledge", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("nonOfMyFamilyMembersRegistered", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FFPB_RegistrationVersion (beneficiaryVersionId LONG not null primary key,beneficiaryId LONG,groupId LONG,companyId LONG,version DOUBLE,name VARCHAR(75) null,mobileNumber VARCHAR(75) null,nationalId LONG,emailAddress VARCHAR(75) null,cardNumber VARCHAR(75) null,dateOfBirth DATE null,gender INTEGER,fatherName VARCHAR(75) null,motherName VARCHAR(75) null,maritalStatus INTEGER,spouseName VARCHAR(75) null,spouseFatherName VARCHAR(75) null,spouseDateOfBirth DATE null,spouseNationalId LONG,familyAverageMonthlyIncome VARCHAR(75) null,familyEarningMembers INTEGER,acknowledge BOOLEAN,nonOfMyFamilyMembersRegistered BOOLEAN,status INTEGER,statusByUserId LONG,statusDate DATE null,createdBy LONG,createDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table FFPB_RegistrationVersion";

	public static final String ORDER_BY_JPQL =
		" ORDER BY ffpBeneficiaryVersion.beneficiaryId DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FFPB_RegistrationVersion.beneficiaryId DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BENEFICIARYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long VERSION_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FFPBeneficiaryVersionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _beneficiaryVersionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBeneficiaryVersionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _beneficiaryVersionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FFPBeneficiaryVersion.class;
	}

	@Override
	public String getModelClassName() {
		return FFPBeneficiaryVersion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FFPBeneficiaryVersion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FFPBeneficiaryVersion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FFPBeneficiaryVersion, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FFPBeneficiaryVersion)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FFPBeneficiaryVersion, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FFPBeneficiaryVersion, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FFPBeneficiaryVersion)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FFPBeneficiaryVersion, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FFPBeneficiaryVersion, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<FFPBeneficiaryVersion, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<FFPBeneficiaryVersion, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<FFPBeneficiaryVersion, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<FFPBeneficiaryVersion, Object>>();
		Map<String, BiConsumer<FFPBeneficiaryVersion, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<FFPBeneficiaryVersion, ?>>();

		attributeGetterFunctions.put(
			"beneficiaryVersionId",
			FFPBeneficiaryVersion::getBeneficiaryVersionId);
		attributeSetterBiConsumers.put(
			"beneficiaryVersionId",
			(BiConsumer<FFPBeneficiaryVersion, Long>)
				FFPBeneficiaryVersion::setBeneficiaryVersionId);
		attributeGetterFunctions.put(
			"beneficiaryId", FFPBeneficiaryVersion::getBeneficiaryId);
		attributeSetterBiConsumers.put(
			"beneficiaryId",
			(BiConsumer<FFPBeneficiaryVersion, Long>)
				FFPBeneficiaryVersion::setBeneficiaryId);
		attributeGetterFunctions.put(
			"groupId", FFPBeneficiaryVersion::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<FFPBeneficiaryVersion, Long>)
				FFPBeneficiaryVersion::setGroupId);
		attributeGetterFunctions.put(
			"companyId", FFPBeneficiaryVersion::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<FFPBeneficiaryVersion, Long>)
				FFPBeneficiaryVersion::setCompanyId);
		attributeGetterFunctions.put(
			"version", FFPBeneficiaryVersion::getVersion);
		attributeSetterBiConsumers.put(
			"version",
			(BiConsumer<FFPBeneficiaryVersion, Double>)
				FFPBeneficiaryVersion::setVersion);
		attributeGetterFunctions.put("name", FFPBeneficiaryVersion::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<FFPBeneficiaryVersion, String>)
				FFPBeneficiaryVersion::setName);
		attributeGetterFunctions.put(
			"mobileNumber", FFPBeneficiaryVersion::getMobileNumber);
		attributeSetterBiConsumers.put(
			"mobileNumber",
			(BiConsumer<FFPBeneficiaryVersion, String>)
				FFPBeneficiaryVersion::setMobileNumber);
		attributeGetterFunctions.put(
			"nationalId", FFPBeneficiaryVersion::getNationalId);
		attributeSetterBiConsumers.put(
			"nationalId",
			(BiConsumer<FFPBeneficiaryVersion, Long>)
				FFPBeneficiaryVersion::setNationalId);
		attributeGetterFunctions.put(
			"emailAddress", FFPBeneficiaryVersion::getEmailAddress);
		attributeSetterBiConsumers.put(
			"emailAddress",
			(BiConsumer<FFPBeneficiaryVersion, String>)
				FFPBeneficiaryVersion::setEmailAddress);
		attributeGetterFunctions.put(
			"cardNumber", FFPBeneficiaryVersion::getCardNumber);
		attributeSetterBiConsumers.put(
			"cardNumber",
			(BiConsumer<FFPBeneficiaryVersion, String>)
				FFPBeneficiaryVersion::setCardNumber);
		attributeGetterFunctions.put(
			"dateOfBirth", FFPBeneficiaryVersion::getDateOfBirth);
		attributeSetterBiConsumers.put(
			"dateOfBirth",
			(BiConsumer<FFPBeneficiaryVersion, Date>)
				FFPBeneficiaryVersion::setDateOfBirth);
		attributeGetterFunctions.put(
			"gender", FFPBeneficiaryVersion::getGender);
		attributeSetterBiConsumers.put(
			"gender",
			(BiConsumer<FFPBeneficiaryVersion, Integer>)
				FFPBeneficiaryVersion::setGender);
		attributeGetterFunctions.put(
			"fatherName", FFPBeneficiaryVersion::getFatherName);
		attributeSetterBiConsumers.put(
			"fatherName",
			(BiConsumer<FFPBeneficiaryVersion, String>)
				FFPBeneficiaryVersion::setFatherName);
		attributeGetterFunctions.put(
			"motherName", FFPBeneficiaryVersion::getMotherName);
		attributeSetterBiConsumers.put(
			"motherName",
			(BiConsumer<FFPBeneficiaryVersion, String>)
				FFPBeneficiaryVersion::setMotherName);
		attributeGetterFunctions.put(
			"maritalStatus", FFPBeneficiaryVersion::getMaritalStatus);
		attributeSetterBiConsumers.put(
			"maritalStatus",
			(BiConsumer<FFPBeneficiaryVersion, Integer>)
				FFPBeneficiaryVersion::setMaritalStatus);
		attributeGetterFunctions.put(
			"spouseName", FFPBeneficiaryVersion::getSpouseName);
		attributeSetterBiConsumers.put(
			"spouseName",
			(BiConsumer<FFPBeneficiaryVersion, String>)
				FFPBeneficiaryVersion::setSpouseName);
		attributeGetterFunctions.put(
			"spouseFatherName", FFPBeneficiaryVersion::getSpouseFatherName);
		attributeSetterBiConsumers.put(
			"spouseFatherName",
			(BiConsumer<FFPBeneficiaryVersion, String>)
				FFPBeneficiaryVersion::setSpouseFatherName);
		attributeGetterFunctions.put(
			"spouseDateOfBirth", FFPBeneficiaryVersion::getSpouseDateOfBirth);
		attributeSetterBiConsumers.put(
			"spouseDateOfBirth",
			(BiConsumer<FFPBeneficiaryVersion, Date>)
				FFPBeneficiaryVersion::setSpouseDateOfBirth);
		attributeGetterFunctions.put(
			"spouseNationalId", FFPBeneficiaryVersion::getSpouseNationalId);
		attributeSetterBiConsumers.put(
			"spouseNationalId",
			(BiConsumer<FFPBeneficiaryVersion, Long>)
				FFPBeneficiaryVersion::setSpouseNationalId);
		attributeGetterFunctions.put(
			"familyAverageMonthlyIncome",
			FFPBeneficiaryVersion::getFamilyAverageMonthlyIncome);
		attributeSetterBiConsumers.put(
			"familyAverageMonthlyIncome",
			(BiConsumer<FFPBeneficiaryVersion, String>)
				FFPBeneficiaryVersion::setFamilyAverageMonthlyIncome);
		attributeGetterFunctions.put(
			"familyEarningMembers",
			FFPBeneficiaryVersion::getFamilyEarningMembers);
		attributeSetterBiConsumers.put(
			"familyEarningMembers",
			(BiConsumer<FFPBeneficiaryVersion, Integer>)
				FFPBeneficiaryVersion::setFamilyEarningMembers);
		attributeGetterFunctions.put(
			"acknowledge", FFPBeneficiaryVersion::getAcknowledge);
		attributeSetterBiConsumers.put(
			"acknowledge",
			(BiConsumer<FFPBeneficiaryVersion, Boolean>)
				FFPBeneficiaryVersion::setAcknowledge);
		attributeGetterFunctions.put(
			"nonOfMyFamilyMembersRegistered",
			FFPBeneficiaryVersion::getNonOfMyFamilyMembersRegistered);
		attributeSetterBiConsumers.put(
			"nonOfMyFamilyMembersRegistered",
			(BiConsumer<FFPBeneficiaryVersion, Boolean>)
				FFPBeneficiaryVersion::setNonOfMyFamilyMembersRegistered);
		attributeGetterFunctions.put(
			"status", FFPBeneficiaryVersion::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<FFPBeneficiaryVersion, Integer>)
				FFPBeneficiaryVersion::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", FFPBeneficiaryVersion::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<FFPBeneficiaryVersion, Long>)
				FFPBeneficiaryVersion::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusDate", FFPBeneficiaryVersion::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<FFPBeneficiaryVersion, Date>)
				FFPBeneficiaryVersion::setStatusDate);
		attributeGetterFunctions.put(
			"createdBy", FFPBeneficiaryVersion::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<FFPBeneficiaryVersion, Long>)
				FFPBeneficiaryVersion::setCreatedBy);
		attributeGetterFunctions.put(
			"createDate", FFPBeneficiaryVersion::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<FFPBeneficiaryVersion, Date>)
				FFPBeneficiaryVersion::setCreateDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getBeneficiaryVersionId() {
		return _beneficiaryVersionId;
	}

	@Override
	public void setBeneficiaryVersionId(long beneficiaryVersionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_beneficiaryVersionId = beneficiaryVersionId;
	}

	@JSON
	@Override
	public long getBeneficiaryId() {
		return _beneficiaryId;
	}

	@Override
	public void setBeneficiaryId(long beneficiaryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_beneficiaryId = beneficiaryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalBeneficiaryId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("beneficiaryId"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public double getVersion() {
		return _version;
	}

	@Override
	public void setVersion(double version) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_version = version;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public double getOriginalVersion() {
		return GetterUtil.getDouble(
			this.<Double>getColumnOriginalValue("version"));
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getMobileNumber() {
		if (_mobileNumber == null) {
			return "";
		}
		else {
			return _mobileNumber;
		}
	}

	@Override
	public void setMobileNumber(String mobileNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mobileNumber = mobileNumber;
	}

	@JSON
	@Override
	public long getNationalId() {
		return _nationalId;
	}

	@Override
	public void setNationalId(long nationalId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nationalId = nationalId;
	}

	@JSON
	@Override
	public String getEmailAddress() {
		if (_emailAddress == null) {
			return "";
		}
		else {
			return _emailAddress;
		}
	}

	@Override
	public void setEmailAddress(String emailAddress) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_emailAddress = emailAddress;
	}

	@JSON
	@Override
	public String getCardNumber() {
		if (_cardNumber == null) {
			return "";
		}
		else {
			return _cardNumber;
		}
	}

	@Override
	public void setCardNumber(String cardNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cardNumber = cardNumber;
	}

	@JSON
	@Override
	public Date getDateOfBirth() {
		return _dateOfBirth;
	}

	@Override
	public void setDateOfBirth(Date dateOfBirth) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateOfBirth = dateOfBirth;
	}

	@JSON
	@Override
	public int getGender() {
		return _gender;
	}

	@Override
	public void setGender(int gender) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_gender = gender;
	}

	@JSON
	@Override
	public String getFatherName() {
		if (_fatherName == null) {
			return "";
		}
		else {
			return _fatherName;
		}
	}

	@Override
	public void setFatherName(String fatherName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fatherName = fatherName;
	}

	@JSON
	@Override
	public String getMotherName() {
		if (_motherName == null) {
			return "";
		}
		else {
			return _motherName;
		}
	}

	@Override
	public void setMotherName(String motherName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_motherName = motherName;
	}

	@JSON
	@Override
	public int getMaritalStatus() {
		return _maritalStatus;
	}

	@Override
	public void setMaritalStatus(int maritalStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_maritalStatus = maritalStatus;
	}

	@JSON
	@Override
	public String getSpouseName() {
		if (_spouseName == null) {
			return "";
		}
		else {
			return _spouseName;
		}
	}

	@Override
	public void setSpouseName(String spouseName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_spouseName = spouseName;
	}

	@JSON
	@Override
	public String getSpouseFatherName() {
		if (_spouseFatherName == null) {
			return "";
		}
		else {
			return _spouseFatherName;
		}
	}

	@Override
	public void setSpouseFatherName(String spouseFatherName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_spouseFatherName = spouseFatherName;
	}

	@JSON
	@Override
	public Date getSpouseDateOfBirth() {
		return _spouseDateOfBirth;
	}

	@Override
	public void setSpouseDateOfBirth(Date spouseDateOfBirth) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_spouseDateOfBirth = spouseDateOfBirth;
	}

	@JSON
	@Override
	public long getSpouseNationalId() {
		return _spouseNationalId;
	}

	@Override
	public void setSpouseNationalId(long spouseNationalId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_spouseNationalId = spouseNationalId;
	}

	@JSON
	@Override
	public String getFamilyAverageMonthlyIncome() {
		if (_familyAverageMonthlyIncome == null) {
			return "";
		}
		else {
			return _familyAverageMonthlyIncome;
		}
	}

	@Override
	public void setFamilyAverageMonthlyIncome(
		String familyAverageMonthlyIncome) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_familyAverageMonthlyIncome = familyAverageMonthlyIncome;
	}

	@JSON
	@Override
	public int getFamilyEarningMembers() {
		return _familyEarningMembers;
	}

	@Override
	public void setFamilyEarningMembers(int familyEarningMembers) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_familyEarningMembers = familyEarningMembers;
	}

	@JSON
	@Override
	public boolean getAcknowledge() {
		return _acknowledge;
	}

	@JSON
	@Override
	public boolean isAcknowledge() {
		return _acknowledge;
	}

	@Override
	public void setAcknowledge(boolean acknowledge) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_acknowledge = acknowledge;
	}

	@JSON
	@Override
	public boolean getNonOfMyFamilyMembersRegistered() {
		return _nonOfMyFamilyMembersRegistered;
	}

	@JSON
	@Override
	public boolean isNonOfMyFamilyMembersRegistered() {
		return _nonOfMyFamilyMembersRegistered;
	}

	@Override
	public void setNonOfMyFamilyMembersRegistered(
		boolean nonOfMyFamilyMembersRegistered) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nonOfMyFamilyMembersRegistered = nonOfMyFamilyMembersRegistered;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FFPBeneficiaryVersion.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FFPBeneficiaryVersion toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FFPBeneficiaryVersion>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FFPBeneficiaryVersionImpl ffpBeneficiaryVersionImpl =
			new FFPBeneficiaryVersionImpl();

		ffpBeneficiaryVersionImpl.setBeneficiaryVersionId(
			getBeneficiaryVersionId());
		ffpBeneficiaryVersionImpl.setBeneficiaryId(getBeneficiaryId());
		ffpBeneficiaryVersionImpl.setGroupId(getGroupId());
		ffpBeneficiaryVersionImpl.setCompanyId(getCompanyId());
		ffpBeneficiaryVersionImpl.setVersion(getVersion());
		ffpBeneficiaryVersionImpl.setName(getName());
		ffpBeneficiaryVersionImpl.setMobileNumber(getMobileNumber());
		ffpBeneficiaryVersionImpl.setNationalId(getNationalId());
		ffpBeneficiaryVersionImpl.setEmailAddress(getEmailAddress());
		ffpBeneficiaryVersionImpl.setCardNumber(getCardNumber());
		ffpBeneficiaryVersionImpl.setDateOfBirth(getDateOfBirth());
		ffpBeneficiaryVersionImpl.setGender(getGender());
		ffpBeneficiaryVersionImpl.setFatherName(getFatherName());
		ffpBeneficiaryVersionImpl.setMotherName(getMotherName());
		ffpBeneficiaryVersionImpl.setMaritalStatus(getMaritalStatus());
		ffpBeneficiaryVersionImpl.setSpouseName(getSpouseName());
		ffpBeneficiaryVersionImpl.setSpouseFatherName(getSpouseFatherName());
		ffpBeneficiaryVersionImpl.setSpouseDateOfBirth(getSpouseDateOfBirth());
		ffpBeneficiaryVersionImpl.setSpouseNationalId(getSpouseNationalId());
		ffpBeneficiaryVersionImpl.setFamilyAverageMonthlyIncome(
			getFamilyAverageMonthlyIncome());
		ffpBeneficiaryVersionImpl.setFamilyEarningMembers(
			getFamilyEarningMembers());
		ffpBeneficiaryVersionImpl.setAcknowledge(isAcknowledge());
		ffpBeneficiaryVersionImpl.setNonOfMyFamilyMembersRegistered(
			isNonOfMyFamilyMembersRegistered());
		ffpBeneficiaryVersionImpl.setStatus(getStatus());
		ffpBeneficiaryVersionImpl.setStatusByUserId(getStatusByUserId());
		ffpBeneficiaryVersionImpl.setStatusDate(getStatusDate());
		ffpBeneficiaryVersionImpl.setCreatedBy(getCreatedBy());
		ffpBeneficiaryVersionImpl.setCreateDate(getCreateDate());

		ffpBeneficiaryVersionImpl.resetOriginalValues();

		return ffpBeneficiaryVersionImpl;
	}

	@Override
	public FFPBeneficiaryVersion cloneWithOriginalValues() {
		FFPBeneficiaryVersionImpl ffpBeneficiaryVersionImpl =
			new FFPBeneficiaryVersionImpl();

		ffpBeneficiaryVersionImpl.setBeneficiaryVersionId(
			this.<Long>getColumnOriginalValue("beneficiaryVersionId"));
		ffpBeneficiaryVersionImpl.setBeneficiaryId(
			this.<Long>getColumnOriginalValue("beneficiaryId"));
		ffpBeneficiaryVersionImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		ffpBeneficiaryVersionImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		ffpBeneficiaryVersionImpl.setVersion(
			this.<Double>getColumnOriginalValue("version"));
		ffpBeneficiaryVersionImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		ffpBeneficiaryVersionImpl.setMobileNumber(
			this.<String>getColumnOriginalValue("mobileNumber"));
		ffpBeneficiaryVersionImpl.setNationalId(
			this.<Long>getColumnOriginalValue("nationalId"));
		ffpBeneficiaryVersionImpl.setEmailAddress(
			this.<String>getColumnOriginalValue("emailAddress"));
		ffpBeneficiaryVersionImpl.setCardNumber(
			this.<String>getColumnOriginalValue("cardNumber"));
		ffpBeneficiaryVersionImpl.setDateOfBirth(
			this.<Date>getColumnOriginalValue("dateOfBirth"));
		ffpBeneficiaryVersionImpl.setGender(
			this.<Integer>getColumnOriginalValue("gender"));
		ffpBeneficiaryVersionImpl.setFatherName(
			this.<String>getColumnOriginalValue("fatherName"));
		ffpBeneficiaryVersionImpl.setMotherName(
			this.<String>getColumnOriginalValue("motherName"));
		ffpBeneficiaryVersionImpl.setMaritalStatus(
			this.<Integer>getColumnOriginalValue("maritalStatus"));
		ffpBeneficiaryVersionImpl.setSpouseName(
			this.<String>getColumnOriginalValue("spouseName"));
		ffpBeneficiaryVersionImpl.setSpouseFatherName(
			this.<String>getColumnOriginalValue("spouseFatherName"));
		ffpBeneficiaryVersionImpl.setSpouseDateOfBirth(
			this.<Date>getColumnOriginalValue("spouseDateOfBirth"));
		ffpBeneficiaryVersionImpl.setSpouseNationalId(
			this.<Long>getColumnOriginalValue("spouseNationalId"));
		ffpBeneficiaryVersionImpl.setFamilyAverageMonthlyIncome(
			this.<String>getColumnOriginalValue("familyAverageMonthlyIncome"));
		ffpBeneficiaryVersionImpl.setFamilyEarningMembers(
			this.<Integer>getColumnOriginalValue("familyEarningMembers"));
		ffpBeneficiaryVersionImpl.setAcknowledge(
			this.<Boolean>getColumnOriginalValue("acknowledge"));
		ffpBeneficiaryVersionImpl.setNonOfMyFamilyMembersRegistered(
			this.<Boolean>getColumnOriginalValue(
				"nonOfMyFamilyMembersRegistered"));
		ffpBeneficiaryVersionImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		ffpBeneficiaryVersionImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		ffpBeneficiaryVersionImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		ffpBeneficiaryVersionImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		ffpBeneficiaryVersionImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));

		return ffpBeneficiaryVersionImpl;
	}

	@Override
	public int compareTo(FFPBeneficiaryVersion ffpBeneficiaryVersion) {
		int value = 0;

		if (getBeneficiaryId() < ffpBeneficiaryVersion.getBeneficiaryId()) {
			value = -1;
		}
		else if (getBeneficiaryId() >
					ffpBeneficiaryVersion.getBeneficiaryId()) {

			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FFPBeneficiaryVersion)) {
			return false;
		}

		FFPBeneficiaryVersion ffpBeneficiaryVersion =
			(FFPBeneficiaryVersion)object;

		long primaryKey = ffpBeneficiaryVersion.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FFPBeneficiaryVersion> toCacheModel() {
		FFPBeneficiaryVersionCacheModel ffpBeneficiaryVersionCacheModel =
			new FFPBeneficiaryVersionCacheModel();

		ffpBeneficiaryVersionCacheModel.beneficiaryVersionId =
			getBeneficiaryVersionId();

		ffpBeneficiaryVersionCacheModel.beneficiaryId = getBeneficiaryId();

		ffpBeneficiaryVersionCacheModel.groupId = getGroupId();

		ffpBeneficiaryVersionCacheModel.companyId = getCompanyId();

		ffpBeneficiaryVersionCacheModel.version = getVersion();

		ffpBeneficiaryVersionCacheModel.name = getName();

		String name = ffpBeneficiaryVersionCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			ffpBeneficiaryVersionCacheModel.name = null;
		}

		ffpBeneficiaryVersionCacheModel.mobileNumber = getMobileNumber();

		String mobileNumber = ffpBeneficiaryVersionCacheModel.mobileNumber;

		if ((mobileNumber != null) && (mobileNumber.length() == 0)) {
			ffpBeneficiaryVersionCacheModel.mobileNumber = null;
		}

		ffpBeneficiaryVersionCacheModel.nationalId = getNationalId();

		ffpBeneficiaryVersionCacheModel.emailAddress = getEmailAddress();

		String emailAddress = ffpBeneficiaryVersionCacheModel.emailAddress;

		if ((emailAddress != null) && (emailAddress.length() == 0)) {
			ffpBeneficiaryVersionCacheModel.emailAddress = null;
		}

		ffpBeneficiaryVersionCacheModel.cardNumber = getCardNumber();

		String cardNumber = ffpBeneficiaryVersionCacheModel.cardNumber;

		if ((cardNumber != null) && (cardNumber.length() == 0)) {
			ffpBeneficiaryVersionCacheModel.cardNumber = null;
		}

		Date dateOfBirth = getDateOfBirth();

		if (dateOfBirth != null) {
			ffpBeneficiaryVersionCacheModel.dateOfBirth = dateOfBirth.getTime();
		}
		else {
			ffpBeneficiaryVersionCacheModel.dateOfBirth = Long.MIN_VALUE;
		}

		ffpBeneficiaryVersionCacheModel.gender = getGender();

		ffpBeneficiaryVersionCacheModel.fatherName = getFatherName();

		String fatherName = ffpBeneficiaryVersionCacheModel.fatherName;

		if ((fatherName != null) && (fatherName.length() == 0)) {
			ffpBeneficiaryVersionCacheModel.fatherName = null;
		}

		ffpBeneficiaryVersionCacheModel.motherName = getMotherName();

		String motherName = ffpBeneficiaryVersionCacheModel.motherName;

		if ((motherName != null) && (motherName.length() == 0)) {
			ffpBeneficiaryVersionCacheModel.motherName = null;
		}

		ffpBeneficiaryVersionCacheModel.maritalStatus = getMaritalStatus();

		ffpBeneficiaryVersionCacheModel.spouseName = getSpouseName();

		String spouseName = ffpBeneficiaryVersionCacheModel.spouseName;

		if ((spouseName != null) && (spouseName.length() == 0)) {
			ffpBeneficiaryVersionCacheModel.spouseName = null;
		}

		ffpBeneficiaryVersionCacheModel.spouseFatherName =
			getSpouseFatherName();

		String spouseFatherName =
			ffpBeneficiaryVersionCacheModel.spouseFatherName;

		if ((spouseFatherName != null) && (spouseFatherName.length() == 0)) {
			ffpBeneficiaryVersionCacheModel.spouseFatherName = null;
		}

		Date spouseDateOfBirth = getSpouseDateOfBirth();

		if (spouseDateOfBirth != null) {
			ffpBeneficiaryVersionCacheModel.spouseDateOfBirth =
				spouseDateOfBirth.getTime();
		}
		else {
			ffpBeneficiaryVersionCacheModel.spouseDateOfBirth = Long.MIN_VALUE;
		}

		ffpBeneficiaryVersionCacheModel.spouseNationalId =
			getSpouseNationalId();

		ffpBeneficiaryVersionCacheModel.familyAverageMonthlyIncome =
			getFamilyAverageMonthlyIncome();

		String familyAverageMonthlyIncome =
			ffpBeneficiaryVersionCacheModel.familyAverageMonthlyIncome;

		if ((familyAverageMonthlyIncome != null) &&
			(familyAverageMonthlyIncome.length() == 0)) {

			ffpBeneficiaryVersionCacheModel.familyAverageMonthlyIncome = null;
		}

		ffpBeneficiaryVersionCacheModel.familyEarningMembers =
			getFamilyEarningMembers();

		ffpBeneficiaryVersionCacheModel.acknowledge = isAcknowledge();

		ffpBeneficiaryVersionCacheModel.nonOfMyFamilyMembersRegistered =
			isNonOfMyFamilyMembersRegistered();

		ffpBeneficiaryVersionCacheModel.status = getStatus();

		ffpBeneficiaryVersionCacheModel.statusByUserId = getStatusByUserId();

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			ffpBeneficiaryVersionCacheModel.statusDate = statusDate.getTime();
		}
		else {
			ffpBeneficiaryVersionCacheModel.statusDate = Long.MIN_VALUE;
		}

		ffpBeneficiaryVersionCacheModel.createdBy = getCreatedBy();

		Date createDate = getCreateDate();

		if (createDate != null) {
			ffpBeneficiaryVersionCacheModel.createDate = createDate.getTime();
		}
		else {
			ffpBeneficiaryVersionCacheModel.createDate = Long.MIN_VALUE;
		}

		return ffpBeneficiaryVersionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FFPBeneficiaryVersion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FFPBeneficiaryVersion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FFPBeneficiaryVersion, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(FFPBeneficiaryVersion)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<FFPBeneficiaryVersion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<FFPBeneficiaryVersion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FFPBeneficiaryVersion, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((FFPBeneficiaryVersion)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FFPBeneficiaryVersion>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					FFPBeneficiaryVersion.class, ModelWrapper.class);

	}

	private long _beneficiaryVersionId;
	private long _beneficiaryId;
	private long _groupId;
	private long _companyId;
	private double _version;
	private String _name;
	private String _mobileNumber;
	private long _nationalId;
	private String _emailAddress;
	private String _cardNumber;
	private Date _dateOfBirth;
	private int _gender;
	private String _fatherName;
	private String _motherName;
	private int _maritalStatus;
	private String _spouseName;
	private String _spouseFatherName;
	private Date _spouseDateOfBirth;
	private long _spouseNationalId;
	private String _familyAverageMonthlyIncome;
	private int _familyEarningMembers;
	private boolean _acknowledge;
	private boolean _nonOfMyFamilyMembersRegistered;
	private int _status;
	private long _statusByUserId;
	private Date _statusDate;
	private long _createdBy;
	private Date _createDate;

	public <T> T getColumnValue(String columnName) {
		Function<FFPBeneficiaryVersion, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FFPBeneficiaryVersion)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"beneficiaryVersionId", _beneficiaryVersionId);
		_columnOriginalValues.put("beneficiaryId", _beneficiaryId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("version", _version);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("mobileNumber", _mobileNumber);
		_columnOriginalValues.put("nationalId", _nationalId);
		_columnOriginalValues.put("emailAddress", _emailAddress);
		_columnOriginalValues.put("cardNumber", _cardNumber);
		_columnOriginalValues.put("dateOfBirth", _dateOfBirth);
		_columnOriginalValues.put("gender", _gender);
		_columnOriginalValues.put("fatherName", _fatherName);
		_columnOriginalValues.put("motherName", _motherName);
		_columnOriginalValues.put("maritalStatus", _maritalStatus);
		_columnOriginalValues.put("spouseName", _spouseName);
		_columnOriginalValues.put("spouseFatherName", _spouseFatherName);
		_columnOriginalValues.put("spouseDateOfBirth", _spouseDateOfBirth);
		_columnOriginalValues.put("spouseNationalId", _spouseNationalId);
		_columnOriginalValues.put(
			"familyAverageMonthlyIncome", _familyAverageMonthlyIncome);
		_columnOriginalValues.put(
			"familyEarningMembers", _familyEarningMembers);
		_columnOriginalValues.put("acknowledge", _acknowledge);
		_columnOriginalValues.put(
			"nonOfMyFamilyMembersRegistered", _nonOfMyFamilyMembersRegistered);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("createDate", _createDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("beneficiaryVersionId", 1L);

		columnBitmasks.put("beneficiaryId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("version", 16L);

		columnBitmasks.put("name", 32L);

		columnBitmasks.put("mobileNumber", 64L);

		columnBitmasks.put("nationalId", 128L);

		columnBitmasks.put("emailAddress", 256L);

		columnBitmasks.put("cardNumber", 512L);

		columnBitmasks.put("dateOfBirth", 1024L);

		columnBitmasks.put("gender", 2048L);

		columnBitmasks.put("fatherName", 4096L);

		columnBitmasks.put("motherName", 8192L);

		columnBitmasks.put("maritalStatus", 16384L);

		columnBitmasks.put("spouseName", 32768L);

		columnBitmasks.put("spouseFatherName", 65536L);

		columnBitmasks.put("spouseDateOfBirth", 131072L);

		columnBitmasks.put("spouseNationalId", 262144L);

		columnBitmasks.put("familyAverageMonthlyIncome", 524288L);

		columnBitmasks.put("familyEarningMembers", 1048576L);

		columnBitmasks.put("acknowledge", 2097152L);

		columnBitmasks.put("nonOfMyFamilyMembersRegistered", 4194304L);

		columnBitmasks.put("status", 8388608L);

		columnBitmasks.put("statusByUserId", 16777216L);

		columnBitmasks.put("statusDate", 33554432L);

		columnBitmasks.put("createdBy", 67108864L);

		columnBitmasks.put("createDate", 134217728L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FFPBeneficiaryVersion _escapedModel;

}