/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bd.gov.dgfood.license.management.system.service.base;

import bd.gov.dgfood.license.management.system.model.FGLicenseMDMData;
import bd.gov.dgfood.license.management.system.service.FGLicenseMDMDataLocalService;
import bd.gov.dgfood.license.management.system.service.FGLicenseMDMDataLocalServiceUtil;
import bd.gov.dgfood.license.management.system.service.persistence.FGLicenseDetailsPersistence;
import bd.gov.dgfood.license.management.system.service.persistence.FGLicenseInfoPersistence;
import bd.gov.dgfood.license.management.system.service.persistence.FGLicenseMDMDataPersistence;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the fg license mdm data local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link bd.gov.dgfood.license.management.system.service.impl.FGLicenseMDMDataLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see bd.gov.dgfood.license.management.system.service.impl.FGLicenseMDMDataLocalServiceImpl
 * @generated
 */
public abstract class FGLicenseMDMDataLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, FGLicenseMDMDataLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>FGLicenseMDMDataLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>FGLicenseMDMDataLocalServiceUtil</code>.
	 */

	/**
	 * Adds the fg license mdm data to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FGLicenseMDMDataLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param fgLicenseMDMData the fg license mdm data
	 * @return the fg license mdm data that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FGLicenseMDMData addFGLicenseMDMData(
		FGLicenseMDMData fgLicenseMDMData) {

		fgLicenseMDMData.setNew(true);

		return fgLicenseMDMDataPersistence.update(fgLicenseMDMData);
	}

	/**
	 * Creates a new fg license mdm data with the primary key. Does not add the fg license mdm data to the database.
	 *
	 * @param fgLicenseMDMId the primary key for the new fg license mdm data
	 * @return the new fg license mdm data
	 */
	@Override
	@Transactional(enabled = false)
	public FGLicenseMDMData createFGLicenseMDMData(long fgLicenseMDMId) {
		return fgLicenseMDMDataPersistence.create(fgLicenseMDMId);
	}

	/**
	 * Deletes the fg license mdm data with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FGLicenseMDMDataLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param fgLicenseMDMId the primary key of the fg license mdm data
	 * @return the fg license mdm data that was removed
	 * @throws PortalException if a fg license mdm data with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FGLicenseMDMData deleteFGLicenseMDMData(long fgLicenseMDMId)
		throws PortalException {

		return fgLicenseMDMDataPersistence.remove(fgLicenseMDMId);
	}

	/**
	 * Deletes the fg license mdm data from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FGLicenseMDMDataLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param fgLicenseMDMData the fg license mdm data
	 * @return the fg license mdm data that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FGLicenseMDMData deleteFGLicenseMDMData(
		FGLicenseMDMData fgLicenseMDMData) {

		return fgLicenseMDMDataPersistence.remove(fgLicenseMDMData);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return fgLicenseMDMDataPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			FGLicenseMDMData.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return fgLicenseMDMDataPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>bd.gov.dgfood.license.management.system.model.impl.FGLicenseMDMDataModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return fgLicenseMDMDataPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>bd.gov.dgfood.license.management.system.model.impl.FGLicenseMDMDataModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return fgLicenseMDMDataPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return fgLicenseMDMDataPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return fgLicenseMDMDataPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public FGLicenseMDMData fetchFGLicenseMDMData(long fgLicenseMDMId) {
		return fgLicenseMDMDataPersistence.fetchByPrimaryKey(fgLicenseMDMId);
	}

	/**
	 * Returns the fg license mdm data with the primary key.
	 *
	 * @param fgLicenseMDMId the primary key of the fg license mdm data
	 * @return the fg license mdm data
	 * @throws PortalException if a fg license mdm data with the primary key could not be found
	 */
	@Override
	public FGLicenseMDMData getFGLicenseMDMData(long fgLicenseMDMId)
		throws PortalException {

		return fgLicenseMDMDataPersistence.findByPrimaryKey(fgLicenseMDMId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			fgLicenseMDMDataLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(FGLicenseMDMData.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("fgLicenseMDMId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			fgLicenseMDMDataLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(FGLicenseMDMData.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"fgLicenseMDMId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			fgLicenseMDMDataLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(FGLicenseMDMData.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("fgLicenseMDMId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return fgLicenseMDMDataPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return fgLicenseMDMDataLocalService.deleteFGLicenseMDMData(
			(FGLicenseMDMData)persistedModel);
	}

	@Override
	public BasePersistence<FGLicenseMDMData> getBasePersistence() {
		return fgLicenseMDMDataPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return fgLicenseMDMDataPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the fg license mdm datas.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>bd.gov.dgfood.license.management.system.model.impl.FGLicenseMDMDataModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of fg license mdm datas
	 * @param end the upper bound of the range of fg license mdm datas (not inclusive)
	 * @return the range of fg license mdm datas
	 */
	@Override
	public List<FGLicenseMDMData> getFGLicenseMDMDatas(int start, int end) {
		return fgLicenseMDMDataPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of fg license mdm datas.
	 *
	 * @return the number of fg license mdm datas
	 */
	@Override
	public int getFGLicenseMDMDatasCount() {
		return fgLicenseMDMDataPersistence.countAll();
	}

	/**
	 * Updates the fg license mdm data in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FGLicenseMDMDataLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param fgLicenseMDMData the fg license mdm data
	 * @return the fg license mdm data that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FGLicenseMDMData updateFGLicenseMDMData(
		FGLicenseMDMData fgLicenseMDMData) {

		return fgLicenseMDMDataPersistence.update(fgLicenseMDMData);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			FGLicenseMDMDataLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		fgLicenseMDMDataLocalService = (FGLicenseMDMDataLocalService)aopProxy;

		_setLocalServiceUtilService(fgLicenseMDMDataLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return FGLicenseMDMDataLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return FGLicenseMDMData.class;
	}

	protected String getModelClassName() {
		return FGLicenseMDMData.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = fgLicenseMDMDataPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		FGLicenseMDMDataLocalService fgLicenseMDMDataLocalService) {

		try {
			Field field =
				FGLicenseMDMDataLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, fgLicenseMDMDataLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected FGLicenseDetailsPersistence fgLicenseDetailsPersistence;

	@Reference
	protected FGLicenseInfoPersistence fgLicenseInfoPersistence;

	protected FGLicenseMDMDataLocalService fgLicenseMDMDataLocalService;

	@Reference
	protected FGLicenseMDMDataPersistence fgLicenseMDMDataPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}