create table FFPB_Registration (
	uuid_ VARCHAR(75) null,
	beneficiaryId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	version DOUBLE,
	name VARCHAR(75) null,
	mobileNumber VARCHAR(75) null,
	nationalId LONG,
	emailAddress VARCHAR(75) null,
	cardNumber VARCHAR(75) null,
	dateOfBirth DATE null,
	gender INTEGER,
	fatherName VARCHAR(75) null,
	motherName VARCHAR(75) null,
	maritalStatus INTEGER,
	spouseName VARCHAR(75) null,
	spouseFatherName VARCHAR(75) null,
	spouseDateOfBirth DATE null,
	spouseNationalId LONG,
	familyAverageMonthlyIncome VARCHAR(75) null,
	familyEarningMembers INTEGER,
	acknowledge BOOLEAN,
	nonOfMyFamilyMembersRegistered BOOLEAN,
	status INTEGER,
	statusByUserId LONG,
	statusDate DATE null,
	createdBy LONG,
	createDate DATE null,
	modifiedBy LONG,
	modifiedDate DATE null
);

create table FFPB_RegistrationVersion (
	beneficiaryVersionId LONG not null primary key,
	beneficiaryId LONG,
	groupId LONG,
	companyId LONG,
	version DOUBLE,
	name VARCHAR(75) null,
	mobileNumber VARCHAR(75) null,
	nationalId LONG,
	emailAddress VARCHAR(75) null,
	cardNumber VARCHAR(75) null,
	dateOfBirth DATE null,
	gender INTEGER,
	fatherName VARCHAR(75) null,
	motherName VARCHAR(75) null,
	maritalStatus INTEGER,
	spouseName VARCHAR(75) null,
	spouseFatherName VARCHAR(75) null,
	spouseDateOfBirth DATE null,
	spouseNationalId LONG,
	familyAverageMonthlyIncome VARCHAR(75) null,
	familyEarningMembers INTEGER,
	acknowledge BOOLEAN,
	nonOfMyFamilyMembersRegistered BOOLEAN,
	status INTEGER,
	statusByUserId LONG,
	statusDate DATE null,
	createdBy LONG,
	createDate DATE null
);